connections {
    enterprise-vpn {
        version = 2
        local_addrs  = 172.28.0.2
        remote_addrs = 172.28.0.3
        proposals = aes256gcm16-prfsha384-ecp384-ke1_mlkem768,aes256gcm16-prfsha384-ecp384

        local {
            auth = pubkey
            certs = sunCert.pem
            id = sun.enterprise.net
        }
        remote {
            auth = pubkey
            certs = moonCert.pem
            id = moon.enterprise.net
        }

        children {
            corp-traffic-sa {
                esp_proposals = aes256gcm16-ecp384
                mode = tunnel
                local_ts = 172.28.0.2/32
                remote_ts = 172.28.0.3/32
                rekey_time = 3600
                start_action = none
            }
        }
    }
}
