"""
test_real_pcap_pipeline.py — Verification of IPsec Daemon API & Real PCAP Pipeline.

Tests the full end-to-end SIH-160 analytical pipeline against REAL wire captures (.pcap)
generated by the active Fedora strongSwan Docker testbed:
  - T003: Tunnel Mode AES-256-GCM MODP-2048 IPv4
  - T005: Tunnel Mode AES-256-GCM ECP-256 (Group 19) IPv4
  - T006: Transport Mode AES-128-GCM MODP-2048 IPv4
  - T008: Tunnel Mode AES-256-GCM MODP-2048 IPv6
  - Live strongSwan VICI UNIX Domain Socket query
  - Directory scanning X.509 certificate ingestion
  - REST API / Webhook Daemon ingestion server
"""

import json
import os
import shutil
import sys
import tempfile
import time
import urllib.request
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from cert_engine.daemonApiServer import DaemonApiServer
from cert_engine.daemonCertIngest import ingest_from_vici
from pipeline.integratedPipeline import IntegratedPipeline
from tests.test_daemonCertIngest import _generate_test_cert_pem

_TESTBED_DIR = Path.home() / ".gemini" / "antigravity-ide" / "scratch" / "sih-ipsec-testbed"
if not _TESTBED_DIR.exists():
    _TESTBED_DIR = Path.home() / "sih-ipsec-testbed"

_DATASET_DIR = _TESTBED_DIR / "dataset"
_VICI_SOCKET = _TESTBED_DIR / "shared-vici" / "charon.vici"

_tests = []
_passed = 0
_failed = 0


def register_test(fn):
    _tests.append(fn)
    return fn


@register_test
def test_real_pcap_t003_tunnel_aes_gcm():
    """Verify T003 real capture: AES-256-GCM, DH-14 (MODP-2048), SHA-256, ESP telemetry."""
    pcap_path = _DATASET_DIR / "T003" / "capture.pcap"
    assert pcap_path.is_file(), f"T003 PCAP not found at {pcap_path}"

    with tempfile.TemporaryDirectory() as td:
        out_dir = Path(td)
        pipe = IntegratedPipeline(output_dir=out_dir, auto_export_on_complete=True)
        completed = pipe.process_pcap(pcap_path)

        assert len(completed) >= 1, f"Expected at least 1 completed session, got {completed}"
        spi = completed[0]
        assert spi == "0xbcefbfeb6dcb6f59", f"Unexpected initiator SPI: {spi}"

        session = pipe.aggregator.get_session(spi)
        assert session is not None
        assert session.is_handshake_complete() is True

        # Verify negotiated crypto transforms from real wire proposals
        canon = pipe.aggregator.get_canonical_session_dict(spi)
        props = canon.get("IKE_SA_INIT", {}).get("proposals", [])
        assert len(props) > 0, "No proposals in canonical session"
        transforms = props[0].get("transforms", {})

        enc_transforms = transforms.get("encryption", [])
        assert any(t.get("id") == 20 for t in enc_transforms), "AES-GCM (transform id 20) not found"

        dh_transforms = transforms.get("dh_group", [])
        assert any(t.get("id") == 14 for t in dh_transforms), "MODP-2048 (DH group 14) not found"

        # Verify ESP data plane traffic was captured and processed
        assert len(pipe.latest_flow_verdicts) >= 1, "Flow engine did not record any flow verdicts"

        # Verify exported report artifacts exist
        session_out = out_dir / "sessions" / spi
        assert (session_out / "intermediate_canonical_session.json").is_file()
        assert (session_out / "rfc_compliance_report.json").is_file()
        assert (session_out / "crypto_vector_posture.json").is_file()
        assert (session_out / "unified_rag_payload.json").is_file()

        # Validate unified RAG contents
        with open(session_out / "unified_rag_payload.json") as f:
            rag = json.load(f)
        assert rag.get("session_id") == spi
        assert "cryptographic_posture" in rag.get("summaries", {})
        assert "rfc_compliance" in rag.get("summaries", {})


@register_test
def test_real_pcap_t005_ecp256_curve():
    """Verify T005 real capture: AES-256-GCM with ECP-256 / Group 19 Diffie-Hellman."""
    pcap_path = _DATASET_DIR / "T005" / "capture.pcap"
    assert pcap_path.is_file(), f"T005 PCAP not found at {pcap_path}"

    with tempfile.TemporaryDirectory() as td:
        out_dir = Path(td)
        pipe = IntegratedPipeline(output_dir=out_dir, auto_export_on_complete=True)
        completed = pipe.process_pcap(pcap_path)

        assert len(completed) >= 1
        spi = completed[0]
        assert spi == "0x9f16d4c1f868754d"

        canon = pipe.aggregator.get_canonical_session_dict(spi)
        props = canon.get("IKE_SA_INIT", {}).get("proposals", [])
        transforms = props[0].get("transforms", {})

        dh_transforms = transforms.get("dh_group", [])
        assert any(t.get("id") == 19 for t in dh_transforms), f"Group 19 (ECP-256) not found: {dh_transforms}"


@register_test
def test_real_pcap_t006_transport_mode():
    """Verify T006 real capture: Transport Mode IPsec traffic negotiation."""
    pcap_path = _DATASET_DIR / "T006" / "capture.pcap"
    assert pcap_path.is_file(), f"T006 PCAP not found at {pcap_path}"

    with tempfile.TemporaryDirectory() as td:
        out_dir = Path(td)
        pipe = IntegratedPipeline(output_dir=out_dir, auto_export_on_complete=True)
        completed = pipe.process_pcap(pcap_path)

        assert len(completed) >= 1
        spi = completed[0]
        assert spi == "0x776d648116b0ae32"


@register_test
def test_real_pcap_t008_ipv6_tunnel():
    """Verify T008 real capture: IPv6 tunnel negotiation and endpoint dissection."""
    pcap_path = _DATASET_DIR / "T008" / "capture.pcap"
    assert pcap_path.is_file(), f"T008 PCAP not found at {pcap_path}"

    with tempfile.TemporaryDirectory() as td:
        out_dir = Path(td)
        pipe = IntegratedPipeline(output_dir=out_dir, auto_export_on_complete=True)
        completed = pipe.process_pcap(pcap_path)

        assert len(completed) >= 1
        spi = completed[0]
        assert spi == "0xb89f6554afe31d0a"

        canon = pipe.aggregator.get_canonical_session_dict(spi)
        endpoints = canon.get("common", {}).get("endpoints", {})
        init_ip = endpoints.get("initiator_ip") or canon.get("common", {}).get("src_ip", "")
        assert ":" in init_ip, f"Expected IPv6 address format, got: {init_ip}"


@register_test
def test_daemon_vici_socket_live_ingestion():
    """Verify Method B: strongSwan VICI socket query against live running daemon."""
    assert _VICI_SOCKET.exists(), f"VICI socket not found at {_VICI_SOCKET}"

    vici_meta = ingest_from_vici(str(_VICI_SOCKET))
    assert vici_meta.get("source") == "vici_socket", f"Unexpected source: {vici_meta}"
    assert vici_meta.get("daemon_type") == "strongswan"
    assert "initiator" in vici_meta
    assert "responder" in vici_meta
    assert vici_meta["initiator"]["identity"]["value"] in ("client", "gateway")


@register_test
def test_daemon_directory_scan_ingestion():
    """Verify Method A: Directory scanning for X.509 certs and attachment to session."""
    with tempfile.TemporaryDirectory() as td:
        cert_dir = Path(td)
        leaf_pem = _generate_test_cert_pem("gateway.testbed.internal", is_ca=False)
        (cert_dir / "gateway.crt").write_bytes(leaf_pem)

        pipe = IntegratedPipeline(output_dir=Path(td) / "out")
        spi = "0x1122334455667788"
        pipe.aggregator.ingest_packet({
            "common": {"initiator_spi": spi, "plane": "control", "exchange_type": 34},
            "IKE_SA_INIT": {"exchange": "IKE_SA_INIT", "proposals": []},
            "IKE_AUTH": {"exchange": "IKE_AUTH"}
        })

        success = pipe.ingest_daemon_credentials_from_path(
            initiator_spi=spi,
            cert_dir=cert_dir,
            identity_value="gateway.testbed.internal",
        )
        assert success is True

        canon = pipe.aggregator.get_canonical_session_dict(spi)
        assert "auth_metadata" in canon
        assert canon["auth_metadata"]["source"] == "directory_scan"
        certs = canon["auth_metadata"]["responder"]["certificates"]
        assert len(certs) == 1
        assert "gateway.testbed.internal" in certs[0].get("san", [])


@register_test
def test_daemon_webhook_rest_api_ingestion():
    """Verify Section 4: REST API & Daemon Webhook server integration."""
    with tempfile.TemporaryDirectory() as td:
        pipe = IntegratedPipeline(output_dir=Path(td))
        port = 8991
        server = DaemonApiServer(
            host="127.0.0.1",
            port=port,
            pipeline=pipe,
            vici_socket_path=str(_VICI_SOCKET) if _VICI_SOCKET.exists() else None,
        )
        server.start_background()
        time.sleep(0.3)

        try:
            # 1. Health check
            req = urllib.request.urlopen(f"http://127.0.0.1:{port}/health")
            health = json.loads(req.read().decode())
            assert health.get("status") == "healthy"

            # 2. Ingest real PCAP via API
            pcap_file = _DATASET_DIR / "T003" / "capture.pcap"
            pcap_req = urllib.request.Request(
                f"http://127.0.0.1:{port}/api/v1/pcap",
                data=json.dumps({"pcap_path": str(pcap_file)}).encode(),
                headers={"Content-Type": "application/json"}
            )
            pcap_res = json.loads(urllib.request.urlopen(pcap_req).read().decode())
            assert pcap_res.get("status") == "success"
            spi = pcap_res["completed_sessions"][0]

            # 3. Post daemon credentials via webhook
            cred_payload = {
                "source": "daemon_webhook_test",
                "daemon_type": "strongswan",
                "responder": {
                    "identity": {"type": 2, "value": "vpn-gw.internal"},
                    "auth_method": 14,
                    "certificates": []
                }
            }
            cred_req = urllib.request.Request(
                f"http://127.0.0.1:{port}/api/v1/sessions/{spi}/credentials",
                data=json.dumps(cred_payload).encode(),
                headers={"Content-Type": "application/json"}
            )
            cred_res = json.loads(urllib.request.urlopen(cred_req).read().decode())
            assert cred_res.get("status") == "attached"

            # 4. Query session through REST API
            sess_req = urllib.request.urlopen(f"http://127.0.0.1:{port}/api/v1/sessions/{spi}")
            sess_res = json.loads(sess_req.read().decode())
            assert sess_res.get("session_id") == spi
            assert "canonical_session" in sess_res
            assert "rfc_compliance" in sess_res
        finally:
            server.stop()


def run_all():
    global _passed, _failed
    print("=" * 80)
    print("RUNNING REAL PCAP & DAEMON API PIPELINE TEST SUITE")
    print("=" * 80)
    for fn in _tests:
        try:
            fn()
            _passed += 1
            print(f"  PASS  {fn.__name__}")
        except AssertionError as e:
            _failed += 1
            print(f"  FAIL  {fn.__name__} -> {e}")
        except Exception as e:
            _failed += 1
            print(f"  FAIL  {fn.__name__} -> EXCEPTION: {e}")
    print("=" * 80)
    print(f"RESULTS: {_passed} passed, {_failed} failed, {_passed + _failed} total")
    print("=" * 80)
    return _failed == 0


if __name__ == "__main__":
    sys.exit(0 if run_all() else 1)
