"""
pipeline/ragExporter.py — RAG Layer Data Exporter.

Discovers, reads, validates, and packages all JSON reports generated by the
SIH-160 analytical engines into a unified, sanitized RAG-ready payload.

This module is directly callable by the future RAG integration:
    RAG Model -> export_rag_data(output_dir) -> JSON Data Sources -> Unified Payload
"""

from __future__ import annotations

import json
import logging
import os
import time
from pathlib import Path
from typing import Any

logger = logging.getLogger("pipeline.ragExporter")

# Authoritative list of expected JSON report filenames
REPORT_FILENAMES: dict[str, str] = {
    "canonical_session": "intermediate_canonical_session.json",
    "rfc_compliance": "rfc_compliance_report.json",
    "vector_posture": "crypto_vector_posture.json",
    "cert_health": "certificate_health_report.json",
    "traffic_flow": "traffic_flow_report.json",
}

# Sensitive tokens that must never be emitted into RAG payloads
SENSITIVE_KEY_SUBSTRINGS = (
    "PRIVATE KEY",
    "PRIVATE_KEY",
    "BEGIN RSA PRIVATE",
    "BEGIN EC PRIVATE",
    "BEGIN PRIVATE",
)


def _sanitize_value(val: Any) -> Any:
    """Recursively scrub any sensitive private key strings from payloads."""
    if isinstance(val, str):
        for token in SENSITIVE_KEY_SUBSTRINGS:
            if token in val:
                return "[REDACTED_SENSITIVE_KEY_MATERIAL]"
        return val
    elif isinstance(val, dict):
        return {k: _sanitize_value(v) for k, v in val.items()}
    elif isinstance(val, list):
        return [_sanitize_value(item) for item in val]
    return val


class RagExporter:
    """Discovers, validates, and packages persisted or in-memory reports for RAG consumption."""

    def __init__(self, output_dir: str | Path = "output") -> None:
        self.output_dir = Path(output_dir)

    def discover_files(self, target_dir: Path | None = None) -> dict[str, Path | None]:
        """Scan target directory for expected JSON reports."""
        dir_to_scan = target_dir or self.output_dir
        found: dict[str, Path | None] = {}
        for key, fname in REPORT_FILENAMES.items():
            path = dir_to_scan / fname
            if path.is_file():
                found[key] = path
            else:
                # Check for recursive discovery if inside a session subfolder
                matches = list(dir_to_scan.glob(f"**/{fname}"))
                found[key] = matches[0] if matches else None
        return found

    def load_json_file(self, path: Path) -> tuple[dict[str, Any] | None, str | None]:
        """Load and parse a JSON file, returning (data, error_message)."""
        try:
            with open(path, "r", encoding="utf-8") as f:
                content = json.load(f)
            return _sanitize_value(content), None
        except Exception as e:
            return None, f"Failed to parse {path.name}: {str(e)}"

    def compile_payload(
        self,
        canonical: dict[str, Any] | None = None,
        rfc: dict[str, Any] | None = None,
        vector: dict[str, Any] | None = None,
        cert: dict[str, Any] | None = None,
        flow: dict[str, Any] | None = None,
        export_metadata: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Construct the unified RAG payload merging structured summaries and raw sources."""
        export_meta = export_metadata or {}
        export_meta.setdefault("export_timestamp", time.time())
        export_meta.setdefault("schema_version", "1.0")

        # Extract primary identifiers from canonical session if available
        session_id = (
            canonical.get("session_id")
            or canonical.get("initiator_spi")
            or rfc.get("session_id", "UNKNOWN_SESSION")
            if (canonical or rfc)
            else "UNKNOWN_SESSION"
        )

        metadata: dict[str, Any] = {}
        if canonical and "common" in canonical:
            c = canonical["common"]
            endpoints = c.get("endpoints", {})
            metadata = {
                "initiator_ip": endpoints.get("initiator_ip") or c.get("src_ip"),
                "responder_ip": endpoints.get("responder_ip") or c.get("dst_ip"),
                "initiator_port": endpoints.get("initiator_port") or c.get("src_port", 500),
                "responder_port": endpoints.get("responder_port") or c.get("dst_port", 500),
                "ike_version": c.get("protocol_version") or c.get("ike_version", 2),
                "handshake_duration_ms": c.get("timestamps", {}).get("handshake_duration_ms") or c.get("duration_ms", 0.0),
            }

        # Build high-level domain summaries for quick LLM prompt injection
        posture_summary: dict[str, Any] = {}
        if vector:
            posture_summary = {
                "vector_19d": vector.get("vector_19d", []),
                "closest_policy_anchor": vector.get("best_match"),
                "similarity_score": vector.get("best_score"),
                "cosine_distance": vector.get("best_distance"),
                "policy_rankings": vector.get("rankings", []),
            }

        rfc_summary: dict[str, Any] = {}
        if rfc:
            rfc_summary = {
                "overall_rfc_status": rfc.get("overall_rfc_status"),
                "cryptographic_posture": rfc.get("cryptographic_posture"),
                "pqc_classification": rfc.get("pqc_classification"),
                "critical_failures_count": rfc.get("critical_failures_count", 0),
                "warnings_count": rfc.get("warnings_count", 0),
                "passed_rules_count": rfc.get("passed_rules_count", 0),
                "critical_failures": rfc.get("critical_failures", []),
                "warnings": rfc.get("warnings", []),
                "category_summaries": rfc.get("category_summaries", {}),
            }

        cert_summary: dict[str, Any] = {}
        if cert:
            peers_dict = cert.get("peers") or cert.get("peer_audits", {})
            cert_summary = {
                "overall_health_status": cert.get("overall_health_status"),
                "is_compliant": cert.get("is_compliant"),
                "peers": peers_dict,
                "peer_audits": peers_dict,
                "findings": cert.get("findings", []),
                "remediation_actions": cert.get("remediation_actions", []),
            }

        flow_summary: dict[str, Any] = {}
        if flow:
            flow_summary = {
                "flow_key": flow.get("flow_key"),
                "verdict": flow.get("verdict"),
                "trigger_type": flow.get("trigger_type"),
                "packet_count": flow.get("packet_count"),
                "duration_seconds": flow.get("duration_seconds"),
                "features_sample": {
                    "total_packets": flow.get("features", {}).get("total_packets"),
                    "total_bytes": flow.get("features", {}).get("total_bytes"),
                    "mean_packet_size": flow.get("features", {}).get("mean_packet_size"),
                    "packets_per_second": flow.get("features", {}).get("packets_per_second"),
                    "bytes_per_second": flow.get("features", {}).get("bytes_per_second"),
                }
                if "features" in flow
                else {},
            }

        # Unified RAG payload: preserves complete raw data while offering high-level sections
        unified_payload: dict[str, Any] = {
            "schema_version": export_meta.get("schema_version", "1.0"),
            "export_timestamp": export_meta.get("export_timestamp", time.time()),
            "rag_export_metadata": export_meta,
            "session_id": session_id,
            "metadata": metadata,
            "summaries": {
                "cryptographic_posture": posture_summary,
                "rfc_compliance": rfc_summary,
                "pki_certificate_health": cert_summary,
                "traffic_flow_telemetry": flow_summary,
            },
            # Raw sources preserved entirely without dropping any fields
            "raw_sources": {
                "canonical_session": canonical,
                "rfc_compliance": rfc,
                "vector_posture": vector,
                "cert_health": cert,
                "traffic_flow": flow,
            },
        }

        return _sanitize_value(unified_payload)

    def export(self, target_dir: Path | None = None, write_to_disk: bool = True) -> dict[str, Any]:
        """Perform discovery, load files, compile payload, and optionally save unified JSON."""
        dir_to_scan = Path(target_dir or self.output_dir)
        discovered = self.discover_files(dir_to_scan)

        loaded_sources: dict[str, Any] = {}
        missing_files: list[str] = []
        errors: list[str] = []

        for key, path in discovered.items():
            if path is None:
                missing_files.append(REPORT_FILENAMES[key])
                loaded_sources[key] = None
            else:
                data, err = self.load_json_file(path)
                if err:
                    errors.append(err)
                    loaded_sources[key] = None
                else:
                    loaded_sources[key] = data

        export_meta: dict[str, Any] = {
            "source_directory": str(dir_to_scan),
            "export_timestamp": time.time(),
            "discovered_files": [
                REPORT_FILENAMES[k] for k, v in discovered.items() if v is not None
            ],
            "missing_files": missing_files,
            "errors": errors,
            "total_expected": len(REPORT_FILENAMES),
            "total_found": len(discovered) - len(missing_files),
        }

        payload = self.compile_payload(
            canonical=loaded_sources.get("canonical_session"),
            rfc=loaded_sources.get("rfc_compliance"),
            vector=loaded_sources.get("vector_posture"),
            cert=loaded_sources.get("cert_health"),
            flow=loaded_sources.get("traffic_flow"),
            export_metadata=export_meta,
        )

        if write_to_disk:
            dir_to_scan.mkdir(parents=True, exist_ok=True)
            out_file = dir_to_scan / "unified_rag_payload.json"
            with open(out_file, "w", encoding="utf-8") as f:
                json.dump(payload, f, indent=2)
            logger.info("Persisted unified RAG payload to %s", out_file)

        return payload


def export_rag_data(
    output_dir: str | Path = "output",
    session_id: str | None = None,
    write_to_disk: bool = True,
) -> dict[str, Any]:
    """Public API function for RAG layer consumption.

    Discovers all JSON report files in output_dir (or output_dir/sessions/<session_id>),
    preserves all structures, scrubs private key material, and returns the unified payload.
    """
    target = Path(output_dir)
    if session_id:
        session_subdir = target / "sessions" / session_id
        if session_subdir.is_dir():
            target = session_subdir

    exporter = RagExporter(output_dir=target)
    return exporter.export(target_dir=target, write_to_disk=write_to_disk)


def export_from_memory(
    canonical_dict: dict[str, Any],
    rfc_report_dict: dict[str, Any],
    vector_posture_dict: dict[str, Any],
    cert_report_dict: dict[str, Any],
    flow_report_dict: dict[str, Any] | None = None,
    output_dir: str | Path | None = None,
) -> dict[str, Any]:
    """Public API function to compile RAG payload directly from in-memory engine objects."""
    exporter = RagExporter(output_dir=output_dir or "output")
    meta: dict[str, Any] = {
        "source": "in_memory",
        "export_timestamp": time.time(),
        "missing_files": [] if flow_report_dict else ["traffic_flow_report.json"],
        "errors": [],
    }

    payload = exporter.compile_payload(
        canonical=canonical_dict,
        rfc=rfc_report_dict,
        vector=vector_posture_dict,
        cert=cert_report_dict,
        flow=flow_report_dict,
        export_metadata=meta,
    )

    if output_dir:
        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)
        with open(out_path / "unified_rag_payload.json", "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)

    return payload
