"""
rfcRegistries.py — Authoritative RFC and IANA Registries for IKEv2 and IPsec Algorithms.

Sources:
- RFC 7296 (IKEv2 Protocol)
- RFC 8247 (IKEv2 Cryptographic Algorithm Implementation Requirements)
- RFC 8221 (ESP and AH Cryptographic Algorithm Implementation Requirements)
- RFC 9370 (Multiple Key Exchanges in IKEv2)
- RFC 8784 (Post-quantum Preshared Keys in IKEv2)
- RFC 7427 (Signature Authentication in IKEv2)
- RFC 9242 (Intermediate Exchange in IKEv2)
- RFC 9395 (Deprecation of IKEv1 and Historic Cryptographic Algorithms)
- FIPS 203 (ML-KEM) & FIPS 204 (ML-DSA)
- IANA IKEv2 Parameters Registry
"""

from __future__ import annotations

from typing import Any

from .rfcEngineModels import RequirementLevel, SpecSourceType


# RFC 8247 §2.1: IKEv2 Encryption Algorithms (Transform Type 1)

IKEV2_ENCR_REGISTRY: dict[int, dict[str, Any]] = {
    0: {
        "name": "Reserved",
        "req_level": RequirementLevel.MUST_NOT,
        "is_aead": False,
        "allowed_key_sizes": [],
        "rfc": "RFC 7296",
        "section": "§3.3.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Transform ID 0 is reserved for encryption.",
    },
    1: {
        "name": "ENCR_DES_IV64",
        "req_level": RequirementLevel.MUST_NOT,
        "is_aead": False,
        "allowed_key_sizes": [64],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Single DES with 64-bit IV is insecure and prohibited.",
    },
    2: {
        "name": "ENCR_DES",
        "req_level": RequirementLevel.MUST_NOT,
        "is_aead": False,
        "allowed_key_sizes": [64],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Single DES is broken and strictly prohibited.",
    },
    3: {
        "name": "ENCR_3DES",
        "req_level": RequirementLevel.MUST_NOT,
        "is_aead": False,
        "allowed_key_sizes": [192],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Triple-DES (3DES) is vulnerable to sweet32 and prohibited in RFC 8247.",
    },
    4: {
        "name": "ENCR_RC5",
        "req_level": RequirementLevel.MUST_NOT,
        "is_aead": False,
        "allowed_key_sizes": [],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "RC5 is obsolete and prohibited.",
    },
    5: {
        "name": "ENCR_IDEA",
        "req_level": RequirementLevel.MUST_NOT,
        "is_aead": False,
        "allowed_key_sizes": [128],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "IDEA is obsolete and prohibited.",
    },
    6: {
        "name": "ENCR_CAST",
        "req_level": RequirementLevel.MUST_NOT,
        "is_aead": False,
        "allowed_key_sizes": [128],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "CAST is obsolete and prohibited.",
    },
    7: {
        "name": "ENCR_BLOWFISH",
        "req_level": RequirementLevel.MUST_NOT,
        "is_aead": False,
        "allowed_key_sizes": [128, 192, 256, 448],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Blowfish has 64-bit block size and is prohibited.",
    },
    11: {
        "name": "ENCR_NULL",
        "req_level": RequirementLevel.MUST_NOT,
        "is_aead": False,
        "allowed_key_sizes": [],
        "rfc": "RFC 7296 / RFC 8247",
        "section": "§3.3.2 / §2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "ENCR_NULL is strictly prohibited for IKE SA encryption.",
    },
    12: {
        "name": "ENCR_AES_CBC",
        "req_level": RequirementLevel.MUST,
        "is_aead": False,
        "allowed_key_sizes": [128, 256],
        "discouraged_key_sizes": [192],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-CBC is MUST with 128/256-bit keys; 192-bit is SHOULD NOT.",
    },
    13: {
        "name": "ENCR_AES_CTR",
        "req_level": RequirementLevel.MAY,
        "is_aead": False,
        "allowed_key_sizes": [128, 192, 256],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-CTR is MAY.",
    },
    14: {
        "name": "ENCR_AES_CCM_8",
        "req_level": RequirementLevel.SHOULD_NOT,
        "is_aead": True,
        "allowed_key_sizes": [128, 256],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-CCM with 8-octet ICV is SHOULD NOT.",
    },
    15: {
        "name": "ENCR_AES_CCM_12",
        "req_level": RequirementLevel.SHOULD_NOT,
        "is_aead": True,
        "allowed_key_sizes": [128, 256],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-CCM with 12-octet ICV is SHOULD NOT.",
    },
    16: {
        "name": "ENCR_AES_CCM_16",
        "req_level": RequirementLevel.SHOULD,
        "is_aead": True,
        "allowed_key_sizes": [128, 256],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-CCM with 16-octet ICV is SHOULD.",
    },
    18: {
        "name": "ENCR_AES_GCM_8",
        "req_level": RequirementLevel.SHOULD_NOT,
        "is_aead": True,
        "allowed_key_sizes": [128, 256],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-GCM with 8-octet ICV is SHOULD NOT for IKE SA.",
    },
    19: {
        "name": "ENCR_AES_GCM_12",
        "req_level": RequirementLevel.SHOULD_NOT,
        "is_aead": True,
        "allowed_key_sizes": [128, 256],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-GCM with 12-octet ICV is SHOULD NOT for IKE SA.",
    },
    20: {
        "name": "ENCR_AES_GCM_16",
        "req_level": RequirementLevel.MUST,
        "is_aead": True,
        "allowed_key_sizes": [128, 256],
        "discouraged_key_sizes": [192],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-GCM with 16-octet ICV is MUST with 128/256-bit keys; 192-bit is SHOULD NOT.",
    },
    21: {
        "name": "ENCR_NULL_AUTH_AES_GMAC",
        "req_level": RequirementLevel.MUST_NOT,
        "is_aead": True,
        "allowed_key_sizes": [128, 192, 256],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "ENCR_NULL_AUTH_AES_GMAC is prohibited for IKE SA.",
    },
    23: {
        "name": "ENCR_CAMELLIA_CBC",
        "req_level": RequirementLevel.MAY,
        "is_aead": False,
        "allowed_key_sizes": [128, 192, 256],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Camellia-CBC is MAY.",
    },
    24: {
        "name": "ENCR_CAMELLIA_CTR",
        "req_level": RequirementLevel.MAY,
        "is_aead": False,
        "allowed_key_sizes": [128, 192, 256],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Camellia-CTR is MAY.",
    },
    28: {
        "name": "ENCR_CHACHA20_POLY1305",
        "req_level": RequirementLevel.SHOULD,
        "is_aead": True,
        "allowed_key_sizes": [256],
        "rfc": "RFC 8247",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "ChaCha20-Poly1305 is SHOULD with 256-bit key.",
    },
}

# Set of all AEAD Encryption Algorithm IDs
AEAD_ENCR_IDS: frozenset[int] = frozenset({
    14, 15, 16, 18, 19, 20, 21, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35
})


# RFC 8247 §2.2: IKEv2 Pseudorandom Functions (PRF) (Transform Type 2)

IKEV2_PRF_REGISTRY: dict[int, dict[str, Any]] = {
    0: {
        "name": "Reserved",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 7296",
        "section": "§3.3.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Transform ID 0 is reserved for PRF.",
    },
    1: {
        "name": "PRF_HMAC_MD5",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 8247",
        "section": "§2.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "MD5 PRF is cryptographically broken and prohibited.",
    },
    2: {
        "name": "PRF_HMAC_SHA1",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 8247",
        "section": "§2.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "SHA-1 PRF is deprecated and prohibited in RFC 8247.",
    },
    3: {
        "name": "PRF_HMAC_TIGER",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 8247",
        "section": "§2.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "TIGER PRF is obsolete and prohibited.",
    },
    4: {
        "name": "PRF_AES128_XCBC",
        "req_level": RequirementLevel.SHOULD_NOT,
        "rfc": "RFC 8247",
        "section": "§2.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES128-XCBC PRF is SHOULD NOT.",
    },
    5: {
        "name": "PRF_HMAC_SHA2_256",
        "req_level": RequirementLevel.MUST,
        "rfc": "RFC 8247",
        "section": "§2.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-SHA2-256 PRF is MUST.",
    },
    6: {
        "name": "PRF_HMAC_SHA2_384",
        "req_level": RequirementLevel.SHOULD,
        "rfc": "RFC 8247",
        "section": "§2.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-SHA2-384 PRF is SHOULD.",
    },
    7: {
        "name": "PRF_HMAC_SHA2_512",
        "req_level": RequirementLevel.SHOULD,
        "rfc": "RFC 8247",
        "section": "§2.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-SHA2-512 PRF is SHOULD.",
    },
    8: {
        "name": "PRF_AES128_CMAC",
        "req_level": RequirementLevel.SHOULD_NOT,
        "rfc": "RFC 8247",
        "section": "§2.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES128-CMAC PRF is SHOULD NOT.",
    },
}


# RFC 8247 §2.3: IKEv2 Integrity Algorithms (Transform Type 3)

IKEV2_INTEG_REGISTRY: dict[int, dict[str, Any]] = {
    0: {
        "name": "NONE",
        "req_level": RequirementLevel.MUST,  # Permitted ONLY with AEAD
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Integrity NONE is MUST when AEAD is negotiated; MUST NOT when non-AEAD cipher is used.",
    },
    1: {
        "name": "AUTH_HMAC_MD5_96",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-MD5-96 integrity is cryptographically broken and prohibited.",
    },
    2: {
        "name": "AUTH_HMAC_SHA1_96",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-SHA1-96 integrity is deprecated and prohibited in RFC 8247.",
    },
    3: {
        "name": "AUTH_DES_MAC",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "DES-MAC is broken and prohibited.",
    },
    4: {
        "name": "AUTH_KPDK_MD5",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "KPDK-MD5 is broken and prohibited.",
    },
    5: {
        "name": "AUTH_AES_XCBC_96",
        "req_level": RequirementLevel.SHOULD_NOT,
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-XCBC-96 is SHOULD NOT.",
    },
    6: {
        "name": "AUTH_HMAC_MD5_128",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-MD5-128 is broken and prohibited.",
    },
    7: {
        "name": "AUTH_HMAC_SHA1_160",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-SHA1-160 is deprecated and prohibited.",
    },
    8: {
        "name": "AUTH_AES_CMAC_96",
        "req_level": RequirementLevel.SHOULD_NOT,
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-CMAC-96 is SHOULD NOT.",
    },
    9: {
        "name": "AUTH_AES_128_GMAC",
        "req_level": RequirementLevel.MAY,
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-128-GMAC is MAY.",
    },
    10: {
        "name": "AUTH_AES_192_GMAC",
        "req_level": RequirementLevel.SHOULD_NOT,
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-192-GMAC is SHOULD NOT.",
    },
    11: {
        "name": "AUTH_AES_256_GMAC",
        "req_level": RequirementLevel.MAY,
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-256-GMAC is MAY.",
    },
    12: {
        "name": "AUTH_HMAC_SHA2_256_128",
        "req_level": RequirementLevel.MUST,
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-SHA2-256-128 is MUST.",
    },
    13: {
        "name": "AUTH_HMAC_SHA2_384_192",
        "req_level": RequirementLevel.SHOULD,
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-SHA2-384-192 is SHOULD.",
    },
    14: {
        "name": "AUTH_HMAC_SHA2_512_256",
        "req_level": RequirementLevel.SHOULD,
        "rfc": "RFC 8247",
        "section": "§2.3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-SHA2-512-256 is SHOULD.",
    },
}


# RFC 8247 §2.4: Diffie-Hellman / Key Exchange Methods (Transform Type 4)

IKEV2_DH_REGISTRY: dict[int, dict[str, Any]] = {
    0: {
        "name": "NONE",
        "req_level": RequirementLevel.MUST_NOT,
        "type": "NONE",
        "bits": 0,
        "rfc": "RFC 7296",
        "section": "§3.3.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Key exchange NONE is prohibited for IKE_SA_INIT (permitted only for Child SA without PFS).",
    },
    1: {
        "name": "768-bit MODP Group",
        "req_level": RequirementLevel.MUST_NOT,
        "type": "CLASSICAL",
        "bits": 64,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "768-bit MODP is practically breakable and prohibited.",
    },
    2: {
        "name": "1024-bit MODP Group",
        "req_level": RequirementLevel.MUST_NOT,
        "type": "CLASSICAL",
        "bits": 80,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "1024-bit MODP (Group 2) is weak and prohibited.",
    },
    5: {
        "name": "1536-bit MODP Group",
        "req_level": RequirementLevel.MUST_NOT,
        "type": "CLASSICAL",
        "bits": 88,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "1536-bit MODP (Group 5) is insufficient and prohibited.",
    },
    14: {
        "name": "2048-bit MODP Group",
        "req_level": RequirementLevel.MUST,
        "type": "CLASSICAL",
        "bits": 112,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "2048-bit MODP is MUST.",
    },
    15: {
        "name": "3072-bit MODP Group",
        "req_level": RequirementLevel.SHOULD,
        "type": "CLASSICAL",
        "bits": 128,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "3072-bit MODP is SHOULD.",
    },
    16: {
        "name": "4096-bit MODP Group",
        "req_level": RequirementLevel.SHOULD,
        "type": "CLASSICAL",
        "bits": 150,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "4096-bit MODP is SHOULD.",
    },
    17: {
        "name": "6144-bit MODP Group",
        "req_level": RequirementLevel.MAY,
        "type": "CLASSICAL",
        "bits": 192,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "6144-bit MODP is MAY.",
    },
    18: {
        "name": "8192-bit MODP Group",
        "req_level": RequirementLevel.MAY,
        "type": "CLASSICAL",
        "bits": 256,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "8192-bit MODP is MAY.",
    },
    19: {
        "name": "256-bit random ECP group (P-256)",
        "req_level": RequirementLevel.SHOULD,
        "type": "CLASSICAL",
        "bits": 128,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "256-bit random ECP (NIST P-256) is SHOULD.",
    },
    20: {
        "name": "384-bit random ECP group (P-384)",
        "req_level": RequirementLevel.SHOULD,
        "type": "CLASSICAL",
        "bits": 192,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "384-bit random ECP (NIST P-384) is SHOULD.",
    },
    21: {
        "name": "521-bit random ECP group (P-521)",
        "req_level": RequirementLevel.MAY,
        "type": "CLASSICAL",
        "bits": 256,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "521-bit random ECP (NIST P-521) is MAY.",
    },
    22: {
        "name": "1024-bit MODP with 160-bit prime",
        "req_level": RequirementLevel.MUST_NOT,
        "type": "CLASSICAL",
        "bits": 80,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "1024-bit MODP with 160-bit prime is prohibited.",
    },
    25: {
        "name": "192-bit random ECP group",
        "req_level": RequirementLevel.MUST_NOT,
        "type": "CLASSICAL",
        "bits": 96,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "192-bit random ECP is prohibited.",
    },
    26: {
        "name": "224-bit random ECP group",
        "req_level": RequirementLevel.MUST_NOT,
        "type": "CLASSICAL",
        "bits": 112,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "224-bit random ECP is prohibited.",
    },
    27: {
        "name": "brainpoolP224r1",
        "req_level": RequirementLevel.SHOULD_NOT,
        "type": "CLASSICAL",
        "bits": 112,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "brainpoolP224r1 is SHOULD NOT.",
    },
    28: {
        "name": "brainpoolP256r1",
        "req_level": RequirementLevel.SHOULD_NOT,
        "type": "CLASSICAL",
        "bits": 128,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "brainpoolP256r1 is SHOULD NOT.",
    },
    29: {
        "name": "brainpoolP384r1",
        "req_level": RequirementLevel.SHOULD_NOT,
        "type": "CLASSICAL",
        "bits": 192,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "brainpoolP384r1 is SHOULD NOT.",
    },
    30: {
        "name": "brainpoolP512r1",
        "req_level": RequirementLevel.SHOULD_NOT,
        "type": "CLASSICAL",
        "bits": 256,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "brainpoolP512r1 is SHOULD NOT.",
    },
    31: {
        "name": "Curve25519",
        "req_level": RequirementLevel.MUST,
        "type": "CLASSICAL",
        "bits": 128,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Curve25519 is MUST.",
    },
    32: {
        "name": "Curve448",
        "req_level": RequirementLevel.MAY,
        "type": "CLASSICAL",
        "bits": 224,
        "rfc": "RFC 8247",
        "section": "§2.4",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Curve448 is MAY.",
    },
    # ── PQC KEMs (FIPS 203 & IANA Registry) ───────────────────────────
    35: {
        "name": "ml-kem-512",
        "req_level": RequirementLevel.MAY,
        "type": "PQC",
        "bits": 128,
        "rfc": "IANA Registry / FIPS 203",
        "section": "Transform Type 4",
        "spec_source": SpecSourceType.FIPS_STANDARD,
        "reason": "ML-KEM-512 (NIST FIPS 203 Category 1).",
    },
    36: {
        "name": "ml-kem-768",
        "req_level": RequirementLevel.MAY,
        "type": "PQC",
        "bits": 192,
        "rfc": "IANA Registry / FIPS 203",
        "section": "Transform Type 4",
        "spec_source": SpecSourceType.FIPS_STANDARD,
        "reason": "ML-KEM-768 (NIST FIPS 203 Category 3).",
    },
    37: {
        "name": "ml-kem-1024",
        "req_level": RequirementLevel.MAY,
        "type": "PQC",
        "bits": 256,
        "rfc": "IANA Registry / FIPS 203",
        "section": "Transform Type 4",
        "spec_source": SpecSourceType.FIPS_STANDARD,
        "reason": "ML-KEM-1024 (NIST FIPS 203 Category 5).",
    },
    38: {
        "name": "FrodoKEM-640-AES",
        "req_level": RequirementLevel.MAY,
        "type": "PQC",
        "bits": 128,
        "rfc": "IANA Registry",
        "section": "Transform Type 4",
        "spec_source": SpecSourceType.IANA_REGISTRY,
        "reason": "FrodoKEM-640-AES (IANA Assigned).",
    },
    39: {
        "name": "FrodoKEM-976-AES",
        "req_level": RequirementLevel.MAY,
        "type": "PQC",
        "bits": 192,
        "rfc": "IANA Registry",
        "section": "Transform Type 4",
        "spec_source": SpecSourceType.IANA_REGISTRY,
        "reason": "FrodoKEM-976-AES (IANA Assigned).",
    },
    40: {
        "name": "FrodoKEM-1344-AES",
        "req_level": RequirementLevel.MAY,
        "type": "PQC",
        "bits": 256,
        "rfc": "IANA Registry",
        "section": "Transform Type 4",
        "spec_source": SpecSourceType.IANA_REGISTRY,
        "reason": "FrodoKEM-1344-AES (IANA Assigned).",
    },
    # ── Direct Composite / Hybrid Key Exchanges ───────────────────────
    1035: {
        "name": "X25519 + ML-KEM-768",
        "req_level": RequirementLevel.MAY,
        "type": "HYBRID",
        "bits": 192,
        "rfc": "draft-ietf-ipsecme-ikev2-pqc-kem",
        "section": "§3",
        "spec_source": SpecSourceType.INTERNET_DRAFT,
        "reason": "Composite hybrid combining classical X25519 with ML-KEM-768.",
    },
    1036: {
        "name": "ECDH P-256 + ML-KEM-768",
        "req_level": RequirementLevel.MAY,
        "type": "HYBRID",
        "bits": 192,
        "rfc": "draft-ietf-ipsecme-ikev2-pqc-kem",
        "section": "§3",
        "spec_source": SpecSourceType.INTERNET_DRAFT,
        "reason": "Composite hybrid combining classical ECDH P-256 with ML-KEM-768.",
    },
    1037: {
        "name": "X448 + ML-KEM-1024",
        "req_level": RequirementLevel.MAY,
        "type": "HYBRID",
        "bits": 256,
        "rfc": "draft-ietf-ipsecme-ikev2-pqc-kem",
        "section": "§3",
        "spec_source": SpecSourceType.INTERNET_DRAFT,
        "reason": "Composite hybrid combining classical X448 with ML-KEM-1024.",
    },
    1038: {
        "name": "ECDH P-384 + ML-KEM-1024",
        "req_level": RequirementLevel.MAY,
        "type": "HYBRID",
        "bits": 256,
        "rfc": "draft-ietf-ipsecme-ikev2-pqc-kem",
        "section": "§3",
        "spec_source": SpecSourceType.INTERNET_DRAFT,
        "reason": "Composite hybrid combining classical ECDH P-384 with ML-KEM-1024.",
    },
}


# RFC 8221: ESP and AH Cryptographic Requirements

ESP_ENCR_REGISTRY: dict[int, dict[str, Any]] = {
    0: {
        "name": "Reserved",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 8221",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Transform 0 is reserved.",
    },
    2: {
        "name": "ENCR_DES",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 8221",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Single DES is broken and prohibited in ESP.",
    },
    3: {
        "name": "ENCR_3DES",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 8221",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Triple-DES is vulnerable to sweet32 and prohibited in RFC 8221.",
    },
    11: {
        "name": "ENCR_NULL",
        "req_level": RequirementLevel.MUST,  # Permitted with integrity only
        "rfc": "RFC 8221",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "NULL encryption in ESP is MUST (requires integrity algorithm).",
    },
    12: {
        "name": "ENCR_AES_CBC",
        "req_level": RequirementLevel.MUST,
        "allowed_key_sizes": [128, 256],
        "discouraged_key_sizes": [192],
        "rfc": "RFC 8221",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-CBC is MUST in ESP.",
    },
    13: {
        "name": "ENCR_AES_CTR",
        "req_level": RequirementLevel.MAY,
        "allowed_key_sizes": [128, 192, 256],
        "rfc": "RFC 8221",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-CTR is MAY in ESP.",
    },
    20: {
        "name": "ENCR_AES_GCM_16",
        "req_level": RequirementLevel.MUST,
        "allowed_key_sizes": [128, 256],
        "discouraged_key_sizes": [192],
        "rfc": "RFC 8221",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "AES-GCM-16 is MUST in ESP.",
    },
    28: {
        "name": "ENCR_CHACHA20_POLY1305",
        "req_level": RequirementLevel.SHOULD,
        "allowed_key_sizes": [256],
        "rfc": "RFC 8221",
        "section": "§2.1",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "ChaCha20-Poly1305 is SHOULD in ESP.",
    },
}

ESP_INTEG_REGISTRY: dict[int, dict[str, Any]] = {
    0: {
        "name": "NONE",
        "req_level": RequirementLevel.MUST,  # With AEAD only
        "rfc": "RFC 8221",
        "section": "§2.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Integrity NONE is MUST with AEAD; prohibited with non-AEAD or NULL encryption.",
    },
    1: {
        "name": "AUTH_HMAC_MD5_96",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 8221",
        "section": "§2.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-MD5-96 is prohibited in ESP/AH.",
    },
    2: {
        "name": "AUTH_HMAC_SHA1_96",
        "req_level": RequirementLevel.MUST_NOT,
        "rfc": "RFC 8221",
        "section": "§2.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-SHA1-96 is prohibited in ESP/AH.",
    },
    12: {
        "name": "AUTH_HMAC_SHA2_256_128",
        "req_level": RequirementLevel.MUST,
        "rfc": "RFC 8221",
        "section": "§2.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-SHA2-256-128 is MUST in ESP/AH.",
    },
    13: {
        "name": "AUTH_HMAC_SHA2_384_192",
        "req_level": RequirementLevel.SHOULD,
        "rfc": "RFC 8221",
        "section": "§2.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-SHA2-384-192 is SHOULD in ESP/AH.",
    },
    14: {
        "name": "AUTH_HMAC_SHA2_512_256",
        "req_level": RequirementLevel.SHOULD,
        "rfc": "RFC 8221",
        "section": "§2.2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "HMAC-SHA2-512-256 is SHOULD in ESP/AH.",
    },
}


# Authentication Methods & Post-Quantum Signatures

IKEV2_AUTH_METHODS_REGISTRY: dict[int, dict[str, Any]] = {
    1: {
        "name": "RSA Digital Signature",
        "req_level": RequirementLevel.SHOULD_NOT,
        "type": "CLASSICAL",
        "rfc": "RFC 7296 / RFC 7427",
        "section": "§3.8",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Legacy RSA (PKCS#1 v1.5) without hash negotiation; RFC 7427 Digital Signature (14) recommended.",
    },
    2: {
        "name": "Shared Key Message Integrity Code (PSK)",
        "req_level": RequirementLevel.MUST,
        "type": "CLASSICAL",
        "rfc": "RFC 7296",
        "section": "§3.8",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "Pre-Shared Key authentication is MUST.",
    },
    3: {
        "name": "DSS Digital Signature",
        "req_level": RequirementLevel.MUST_NOT,
        "type": "CLASSICAL",
        "rfc": "RFC 8247",
        "section": "§3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "DSS is broken and prohibited.",
    },
    9: {
        "name": "ECDSA with SHA-256 on P-256",
        "req_level": RequirementLevel.SHOULD,
        "type": "CLASSICAL",
        "rfc": "RFC 4754 / RFC 8247",
        "section": "§3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "ECDSA P-256 is SHOULD.",
    },
    10: {
        "name": "ECDSA with SHA-384 on P-384",
        "req_level": RequirementLevel.SHOULD,
        "type": "CLASSICAL",
        "rfc": "RFC 4754 / RFC 8247",
        "section": "§3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "ECDSA P-384 is SHOULD.",
    },
    11: {
        "name": "ECDSA with SHA-512 on P-521",
        "req_level": RequirementLevel.MAY,
        "type": "CLASSICAL",
        "rfc": "RFC 4754 / RFC 8247",
        "section": "§3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "ECDSA P-521 is MAY.",
    },
    13: {
        "name": "NULL Authentication",
        "req_level": RequirementLevel.MAY,
        "type": "CLASSICAL",
        "rfc": "RFC 7619",
        "section": "§2",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "NULL Authentication (RFC 7619) provides opportunistic security without peer verification.",
    },
    14: {
        "name": "Digital Signature",
        "req_level": RequirementLevel.SHOULD,
        "type": "GENERIC_SIGNATURE",
        "rfc": "RFC 7427",
        "section": "§3",
        "spec_source": SpecSourceType.PUBLISHED_RFC,
        "reason": "RFC 7427 Digital Signature with explicit hash negotiation.",
    },
}

# PQC Signature Algorithms (RFC 7427 / IANA / FIPS 204)
PQC_SIG_ALGO_REGISTRY: dict[int, dict[str, Any]] = {
    18: {
        "name": "ML-DSA-44",
        "bits": 128,
        "spec_source": SpecSourceType.FIPS_STANDARD,
        "rfc": "FIPS 204 / IANA",
        "section": "NIST Category 2",
    },
    19: {
        "name": "ML-DSA-65",
        "bits": 192,
        "spec_source": SpecSourceType.FIPS_STANDARD,
        "rfc": "FIPS 204 / IANA",
        "section": "NIST Category 3",
    },
    20: {
        "name": "ML-DSA-87",
        "bits": 256,
        "spec_source": SpecSourceType.FIPS_STANDARD,
        "rfc": "FIPS 204 / IANA",
        "section": "NIST Category 5",
    },
    21: {
        "name": "Falcon-512",
        "bits": 128,
        "spec_source": SpecSourceType.IANA_REGISTRY,
        "rfc": "IANA",
        "section": "NIST Category 1",
    },
    22: {
        "name": "Falcon-1024",
        "bits": 192,
        "spec_source": SpecSourceType.IANA_REGISTRY,
        "rfc": "IANA",
        "section": "NIST Category 5",
    },
    23: {
        "name": "SLH-DSA-SHA2-128s",
        "bits": 128,
        "spec_source": SpecSourceType.FIPS_STANDARD,
        "rfc": "FIPS 205 / IANA",
        "section": "NIST Category 1",
    },
}

# Certificate Key Type OIDs
CERT_KEY_TYPE_OIDS: dict[str, dict[str, Any]] = {
    # PQC
    "2.16.840.1.101.3.4.3.17": {"name": "ML-DSA-44", "type": "PQC", "bits": 128, "source": SpecSourceType.FIPS_STANDARD},
    "2.16.840.1.101.3.4.3.18": {"name": "ML-DSA-65", "type": "PQC", "bits": 192, "source": SpecSourceType.FIPS_STANDARD},
    "2.16.840.1.101.3.4.3.19": {"name": "ML-DSA-87", "type": "PQC", "bits": 256, "source": SpecSourceType.FIPS_STANDARD},
    # Classical
    "1.2.840.113549.1.1.1": {"name": "rsaEncryption", "type": "CLASSICAL", "min_bits": 2048, "source": SpecSourceType.PUBLISHED_RFC},
    "1.2.840.113549.1.1.10": {"name": "RSASSA-PSS", "type": "CLASSICAL", "min_bits": 2048, "source": SpecSourceType.PUBLISHED_RFC},
    "1.2.840.10045.2.1": {"name": "id-ecPublicKey", "type": "CLASSICAL", "min_bits": 256, "source": SpecSourceType.PUBLISHED_RFC},
    "1.3.101.112": {"name": "Ed25519", "type": "CLASSICAL", "min_bits": 256, "source": SpecSourceType.PUBLISHED_RFC},
    "1.3.101.113": {"name": "Ed448", "type": "CLASSICAL", "min_bits": 448, "source": SpecSourceType.PUBLISHED_RFC},
    "1.2.840.10040.4.1": {"name": "dsa", "type": "CLASSICAL", "broken": True, "source": SpecSourceType.PUBLISHED_RFC},
}

# Certificate Signature Algorithm OIDs (Broken / Weak vs Modern)
CERT_SIG_ALGO_OIDS: dict[str, dict[str, Any]] = {
    "1.2.840.113549.1.1.4": {"name": "md5WithRSAEncryption", "broken": True, "reason": "MD5 hash is broken."},
    "1.2.840.113549.1.1.5": {"name": "sha1WithRSAEncryption", "broken": True, "reason": "SHA-1 hash is collision-compromised."},
    "1.2.840.10045.4.1": {"name": "ecdsa-with-SHA1", "broken": True, "reason": "SHA-1 hash is collision-compromised."},
    "1.2.840.10040.4.3": {"name": "dsa-with-sha1", "broken": True, "reason": "DSA with SHA-1 is broken."},
    "1.2.840.113549.1.1.11": {"name": "sha256WithRSAEncryption", "broken": False},
    "1.2.840.113549.1.1.12": {"name": "sha384WithRSAEncryption", "broken": False},
    "1.2.840.113549.1.1.13": {"name": "sha512WithRSAEncryption", "broken": False},
    "1.2.840.10045.4.3.2": {"name": "ecdsa-with-SHA256", "broken": False},
    "1.2.840.10045.4.3.3": {"name": "ecdsa-with-SHA384", "broken": False},
    "1.2.840.10045.4.3.4": {"name": "ecdsa-with-SHA512", "broken": False},
    "2.16.840.1.101.3.4.3.17": {"name": "ML-DSA-44", "broken": False, "pqc": True},
    "2.16.840.1.101.3.4.3.18": {"name": "ML-DSA-65", "broken": False, "pqc": True},
    "2.16.840.1.101.3.4.3.19": {"name": "ML-DSA-87", "broken": False, "pqc": True},
}


# Key Notify Types (RFC 7296, 7427, 8784, 9242, 9370)

NOTIFY_TYPES = {
    16388: "NAT_DETECTION_SOURCE_IP",          # RFC 7296 §2.23
    16389: "NAT_DETECTION_DESTINATION_IP",     # RFC 7296 §2.23
    16393: "REKEY_SA",                         # RFC 7296 §1.3.3
    16430: "IKEV2_FRAGMENTATION_SUPPORTED",    # RFC 7383
    16431: "SIGNATURE_HASH_ALGORITHMS_PRE",    # Draft-era alias
    16435: "USE_PPK",                          # RFC 8784
    16436: "PPK_IDENTITY",                     # RFC 8784
    16437: "NO_PPK_AUTH",                      # RFC 8784
    16438: "INTERMEDIATE_EXCHANGE_SUPPORTED",  # RFC 9242
    16440: "ADDITIONAL_KEY_EXCHANGE",          # RFC 9370
    16443: "SIGNATURE_HASH_ALGORITHMS",        # RFC 7427
}
