'use client';

import React, { useState } from 'react';
import { FileCheck, Check, AlertTriangle, XCircle, Search, Shield, Filter } from 'lucide-react';

interface RfcRule {
  code: string;
  rfc: string;
  title: string;
  status: 'PASS' | 'WARN' | 'FAIL';
  category: 'IKEv2' | 'ESP' | 'REKEY' | 'CRYPTO';
  description: string;
  impact: string;
}

const RFC_RULES: RfcRule[] = [
  {
    code: 'RFC-C-001',
    rfc: 'RFC 7296 §1.2',
    title: 'IKE_SA_INIT Nonce Length Verification',
    status: 'PASS',
    category: 'IKEv2',
    description: 'Nonces Ni and Nr MUST be between 16 and 256 octets in length and generated by a cryptographically secure PRNG.',
    impact: 'Prevents nonce truncation and replay vulnerabilities.',
  },
  {
    code: 'RFC-C-004',
    rfc: 'RFC 7296 §2.8',
    title: 'Cryptographic Transform Proposal Structure',
    status: 'PASS',
    category: 'IKEv2',
    description: 'Proposals must contain at least one valid ENCR, PRF, and INTEG or AEAD transform matching RFC 8221 requirements.',
    impact: 'Prevents cipher downgrade attacks.',
  },
  {
    code: 'RFC-C-027',
    rfc: 'RFC 7296 §1.3',
    title: 'CREATE_CHILD_SA Rekey PFS Enforcement',
    status: 'WARN',
    category: 'REKEY',
    description: 'When rekeying a Child SA, a fresh Diffie-Hellman Key Exchange payload (KEi/KEr) should be included to ensure Perfect Forward Secrecy.',
    impact: 'Session retains key material from parent IKE SA, exposing historical traffic if master key is compromised.',
  },
  {
    code: 'RFC-C-012',
    rfc: 'RFC 4303 §3.3.3',
    title: 'Anti-Replay Window Sliding Verification',
    status: 'PASS',
    category: 'ESP',
    description: 'ESP receiver must maintain a sequence number window (minimum 64 packets with 64-bit Extended Sequence Numbers).',
    impact: 'Blocks packet reinjection and packet multiplication attacks.',
  },
  {
    code: 'RFC-C-033',
    rfc: 'RFC 4301 §4.4.1',
    title: 'Security Policy Database (SPD) Selector Match',
    status: 'PASS',
    category: 'ESP',
    description: 'Inbound packet selectors (Source, Destination, Protocol, Ports) must strictly match the negotiating Traffic Selector (TSi/TSr).',
    impact: 'Blocks cross-tunnel packet injection and routing bypasses.',
  },
  {
    code: 'SEC-D09',
    rfc: 'NTRO 26160 Baseline',
    title: 'Perimeter Gateway SA Lifetime Ceiling',
    status: 'WARN',
    category: 'REKEY',
    description: 'Operational perimeter gateways must enforce Child SA renegotiation intervals not exceeding 7,200 seconds (2 hours) or 10GB.',
    impact: 'High-volume session exposure limits key-exhaustion defense.',
  },
  {
    code: 'RFC-C-088',
    rfc: 'RFC 8221 §5',
    title: 'Deprecated Algorithm Prohibition (3DES & MD5)',
    status: 'PASS',
    category: 'CRYPTO',
    description: 'RFC 8221 MUST NOT negotiate 3DES-CBC or HMAC-MD5 in sovereign defense network security gateways.',
    impact: 'Eliminates known collision attacks and Sweet32 block cipher vulnerabilities.',
  },
];

export default function RfcCompliancePage() {
  const [filter, setFilter] = useState('ALL');
  const [search, setSearch] = useState('');

  const filteredRules = RFC_RULES.filter((r) => {
    if (filter !== 'ALL' && r.status !== filter) return false;
    if (search && !r.title.toLowerCase().includes(search.toLowerCase()) && !r.code.toLowerCase().includes(search.toLowerCase())) {
      return false;
    }
    return true;
  });

  return (
    <div className="space-y-6 font-mono text-xs">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-sentinel-border">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <FileCheck className="w-4 h-4 text-sentinel-copper" />
            <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-sentinel-text uppercase">
              RFC COMPLIANCE & RULE VERIFICATION ENGINE
            </h1>
          </div>
          <p className="text-xs text-sentinel-text-muted">
            Formal deterministic compliance audit against RFC 7296, RFC 4301, RFC 4303, and Sovereign Defense Baselines.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <div className="text-right text-[11px]">
            <div className="text-sentinel-mint font-bold">87% PASSED (18 / 24)</div>
            <div className="text-sentinel-text-muted">4 Warnings • 2 Non-Compliant</div>
          </div>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-3 p-3.5 rounded-lg border border-sentinel-border bg-[#101214]">
        <div className="flex items-center gap-2 w-full sm:w-auto">
          <button
            onClick={() => setFilter('ALL')}
            className={`px-3 py-1 rounded text-[11px] font-bold ${filter === 'ALL' ? 'bg-sentinel-copper text-white' : 'text-sentinel-text-muted hover:text-sentinel-text'}`}
          >
            ALL RULES (24)
          </button>
          <button
            onClick={() => setFilter('PASS')}
            className={`px-3 py-1 rounded text-[11px] font-bold ${filter === 'PASS' ? 'bg-sentinel-mint text-black' : 'text-sentinel-text-muted hover:text-sentinel-text'}`}
          >
            PASSED (18)
          </button>
          <button
            onClick={() => setFilter('WARN')}
            className={`px-3 py-1 rounded text-[11px] font-bold ${filter === 'WARN' ? 'bg-sentinel-warning text-black' : 'text-sentinel-text-muted hover:text-sentinel-text'}`}
          >
            WARNINGS (4)
          </button>
          <button
            onClick={() => setFilter('FAIL')}
            className={`px-3 py-1 rounded text-[11px] font-bold ${filter === 'FAIL' ? 'bg-sentinel-critical text-white' : 'text-sentinel-text-muted hover:text-sentinel-text'}`}
          >
            FAILURES (2)
          </button>
        </div>

        <div className="w-full sm:w-64">
          <input
            type="text"
            placeholder="Filter RFC or rule..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full px-3 py-1 rounded border border-sentinel-border bg-[#151719] text-sentinel-text placeholder:text-sentinel-text-muted text-xs focus:outline-none focus:border-sentinel-copper"
          />
        </div>
      </div>

      {/* Rules Table */}
      <div className="rounded-xl border border-sentinel-border bg-[#101214] overflow-hidden">
        <div className="p-4 border-b border-sentinel-border/80 flex items-center justify-between text-xs font-bold text-sentinel-text-muted uppercase tracking-wider">
          <span>RULE DEFINITION & SPECIFICATION</span>
          <span>COMPLIANCE STATUS</span>
        </div>

        <div className="divide-y divide-sentinel-border/60">
          {filteredRules.map((rule) => (
            <div key={rule.code} className="p-4 hover:bg-[#151719] transition-colors">
              <div className="flex items-start justify-between gap-4 mb-1.5">
                <div className="flex items-center gap-2.5">
                  <span className="font-bold text-sentinel-copper text-xs px-1.5 py-0.5 rounded border border-sentinel-copper/40 bg-sentinel-copper/10">
                    {rule.code}
                  </span>
                  <span className="text-[11px] font-bold text-sentinel-text-muted">
                    {rule.rfc}
                  </span>
                  <h3 className="font-bold text-sm text-sentinel-text">
                    {rule.title}
                  </h3>
                </div>

                <span
                  className={`text-[10px] px-2 py-0.5 rounded font-bold uppercase shrink-0 ${
                    rule.status === 'PASS'
                      ? 'bg-sentinel-mint/15 text-sentinel-mint border border-sentinel-mint/30'
                      : rule.status === 'WARN'
                      ? 'bg-sentinel-warning/15 text-sentinel-warning border border-sentinel-warning/30'
                      : 'bg-sentinel-critical/15 text-sentinel-critical border border-sentinel-critical/30'
                  }`}
                >
                  {rule.status}
                </span>
              </div>

              <p className="text-xs text-sentinel-text-muted font-sans leading-relaxed mb-2">
                {rule.description}
              </p>

              <div className="text-[11px] text-sentinel-text-muted flex items-center gap-2">
                <span className="text-sentinel-copper font-semibold">Security Impact:</span>
                <span>{rule.impact}</span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
