#!/usr/bin/env python3
"""
generate_report.py — Autonomous AI Security & Cryptographic Compliance Report Generator.

Synthesizes testing outputs generated by the Enterprise Rule Engine (RFC compliance,
19-D cryptographic vector posture, X.509 PKI health, and ESP traffic telemetry)
using Groq LLMs into an exhaustive, publication-grade Executive & Technical Report.

Key Features:
- Discovers and loads all session JSON artifacts from the output/ directory.
- Deep prompt engineering tailored for Executive & Technical evaluation:
    • Quantitative Risk Score (0-100) & Qualitative Risk Meter
    • Comprehensive Multi-Vector Threat Matrix
    • AI Confidence Score with cross-domain diagnostic breakdown
    • Post-Quantum Cryptography (PQC) & CNSA 2.0 readiness audit
    • Explanations of how identified findings can be weaponized / exploited
    • Renderable Mermaid.js sequence, trust chain, and threat architecture diagrams
- Generates both GitHub Flavored Markdown (.md) and an ultra-high-contrast,
  executive-grade interactive HTML dashboard (.html) with Light/Dark theme toggle.
- Automatically saves outputs in the report/ directory with UTC/local timestamps.
- Built-in rate limit resilience (automatic compact payload retry & model fallback).
- Optional --dry-run flag for offline testing and validation without an API key.
- Zero changes to existing codebase.
"""

from __future__ import annotations

import argparse
import datetime
import getpass
import json
import logging
import os
import re
import sys
import time
from pathlib import Path
from typing import Any

# Optional colored output support
try:
    from termcolor import colored
except ImportError:
    def colored(text: str, color: str | None = None, attrs: list[str] | None = None) -> str:
        return text

try:
    from groq import Groq
except ImportError:
    print(colored("Error: 'groq' package is not installed.", "red"))
    print("Please install dependencies using: pip install -r requirements.txt")
    sys.exit(1)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("report_generator")

# Authoritative report filenames expected from analytical engines
EXPECTED_FILENAMES: dict[str, str] = {
    "canonical_session": "intermediate_canonical_session.json",
    "rfc_compliance": "rfc_compliance_report.json",
    "vector_posture": "crypto_vector_posture.json",
    "cert_health": "certificate_health_report.json",
    "traffic_flow": "traffic_flow_report.json",
    "unified_rag": "unified_rag_payload.json",
}

# Substrings that must be sanitized for defense in depth
SENSITIVE_KEY_SUBSTRINGS = (
    "PRIVATE KEY",
    "PRIVATE_KEY",
    "BEGIN RSA PRIVATE",
    "BEGIN EC PRIVATE",
    "BEGIN PRIVATE",
)


def load_env_file(env_path: Path | None = None) -> None:
    """Manually parse .env file if present without requiring external libraries."""
    target = env_path or (Path.cwd() / ".env")
    if not target.is_file():
        return
    try:
        with open(target, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                k = k.strip()
                v = v.strip().strip("'\"")
                if k and k not in os.environ:
                    os.environ[k] = v
        logger.debug("Loaded environment variables from %s", target)
    except Exception as e:
        logger.warning("Could not read .env file: %s", e)


def sanitize_payload(val: Any) -> Any:
    """Recursively scrub any sensitive cryptographic private key material."""
    if isinstance(val, str):
        for token in SENSITIVE_KEY_SUBSTRINGS:
            if token in val:
                return "[REDACTED_SENSITIVE_KEY_MATERIAL]"
        return val
    elif isinstance(val, dict):
        return {k: sanitize_payload(v) for k, v in val.items()}
    elif isinstance(val, list):
        return [sanitize_payload(item) for item in val]
    return val


def discover_session_files(output_dir: Path, session_id: str | None = None) -> dict[str, Path | None]:
    """Locate all expected JSON files in output_dir or output_dir/sessions/<session_id>."""
    target_dir = output_dir
    if session_id:
        sess_path = output_dir / "sessions" / session_id
        if sess_path.is_dir():
            target_dir = sess_path
        elif (output_dir / session_id).is_dir():
            target_dir = output_dir / session_id

    discovered: dict[str, Path | None] = {}
    for key, fname in EXPECTED_FILENAMES.items():
        direct = target_dir / fname
        if direct.is_file():
            discovered[key] = direct
        else:
            # Check recursively in subdirectories
            matches = list(target_dir.glob(f"**/{fname}"))
            discovered[key] = matches[0] if matches else None

    return discovered


def load_all_session_data(output_dir: Path, session_id: str | None = None) -> dict[str, Any]:
    """Ingest, validate, and sanitize all JSON testing outputs."""
    discovered = discover_session_files(output_dir, session_id)
    loaded_data: dict[str, Any] = {}
    file_metadata: list[dict[str, Any]] = []

    for key, path in discovered.items():
        if path and path.is_file():
            try:
                with open(path, "r", encoding="utf-8") as f:
                    raw_content = json.load(f)
                clean_content = sanitize_payload(raw_content)
                loaded_data[key] = clean_content
                file_metadata.append({
                    "role": key,
                    "filename": path.name,
                    "filepath": str(path.resolve()),
                    "size_bytes": path.stat().st_size,
                })
            except Exception as e:
                logger.error("Failed to parse JSON file %s: %s", path, e)
                loaded_data[key] = None
        else:
            loaded_data[key] = None

    # Discover any additional custom JSON files in output_dir
    extra_jsons: dict[str, Any] = {}
    target_dir = output_dir / "sessions" / session_id if session_id else output_dir
    if target_dir.is_dir():
        for p in target_dir.glob("*.json"):
            if p.name not in EXPECTED_FILENAMES.values():
                try:
                    with open(p, "r", encoding="utf-8") as f:
                        extra_jsons[p.stem] = sanitize_payload(json.load(f))
                except Exception:
                    pass

    return {
        "loaded_data": loaded_data,
        "extra_jsons": extra_jsons,
        "file_metadata": file_metadata,
        "target_dir": str(target_dir.resolve()),
    }


def extract_executive_metrics(loaded: dict[str, Any]) -> dict[str, Any]:
    """Synthesize high-level structured metrics for the report and dashboard cards."""
    canon = loaded.get("canonical_session") or {}
    rfc = loaded.get("rfc_compliance") or {}
    vec = loaded.get("vector_posture") or {}
    cert = loaded.get("cert_health") or {}
    flow = loaded.get("traffic_flow") or {}
    rag = loaded.get("unified_rag") or {}

    # Extract session identity
    session_id = (
        canon.get("session_id")
        or rag.get("session_id")
        or (canon.get("common", {}).get("initiator_spi"))
        or rfc.get("session_id", "UNKNOWN_SESSION")
    )

    common = canon.get("common", {})
    endpoints = common.get("endpoints", {})
    src_ip = endpoints.get("initiator_ip") or common.get("src_ip", "N/A")
    dst_ip = endpoints.get("responder_ip") or common.get("dst_ip", "N/A")
    ike_version = common.get("ike_version") or common.get("protocol_version", 2)
    ipsec_mode = canon.get("ipsec_mode") or rfc.get("ipsec_mode", "TUNNEL")

    # RFC Compliance Metrics
    rfc_status = rfc.get("overall_rfc_status", "UNKNOWN")
    pqc_class = rfc.get("pqc_classification", "UNKNOWN")
    hybrid_class = rfc.get("hybrid_classification", "UNKNOWN")
    crypto_posture = rfc.get("cryptographic_posture", "UNKNOWN")
    counts = rfc.get("counts", {})
    passed_rules = counts.get("passed_rules", rfc.get("passed_rules_count", 0))
    failed_rules = counts.get("critical_failures", rfc.get("critical_failures_count", 0))
    warning_rules = counts.get("warnings", rfc.get("warnings_count", 0))
    total_evaluated = counts.get("total_evaluated", passed_rules + failed_rules + warning_rules)

    # 19-D Cryptographic Vector Metrics
    best_anchor = vec.get("best_match", "N/A")
    anchor_display = vec.get("display_name", best_anchor)
    similarity_score = vec.get("best_score", 0.0)
    cosine_distance = vec.get("best_distance", 0.0)
    similarity_pct = f"{similarity_score * 100:.2f}%" if similarity_score else "N/A"
    rankings = vec.get("rankings", [])

    # PKI Certificate Metrics
    cert_status = cert.get("overall_health_status", "UNKNOWN")
    cert_compliant = cert.get("is_compliant", True)
    peers = cert.get("peers") or cert.get("peer_audits", {})
    total_certs = cert.get("summary", {}).get("total_certificates_audited", len(peers))

    # Traffic Flow Metrics
    flow_features = flow.get("features", {})
    packet_count = flow.get("packet_count") or flow_features.get("total_packets", 0)
    total_bytes = flow_features.get("total_bytes", 0)
    mean_pkt_size = flow_features.get("mean_packet_size", 0)
    flow_verdict = flow.get("verdict", "NOMINAL")

    # Preliminary Risk Score Heuristic (0 to 100)
    base_risk = 0.0
    if rfc_status == "FAIL":
        base_risk += 40.0
    elif rfc_status == "WARNING":
        base_risk += 15.0

    if failed_rules > 0:
        base_risk += min(30.0, failed_rules * 10.0)
    if warning_rules > 0:
        base_risk += min(15.0, warning_rules * 5.0)

    if cert_status in ("EXPIRED", "CRITICAL", "REVOKED"):
        base_risk += 35.0
    elif not cert_compliant:
        base_risk += 20.0

    if best_anchor in ("NIST_SP800_131A_DEPRECATED", "LEGACY_BROKEN"):
        base_risk += 35.0
    elif best_anchor == "RFC8247_CLASSICAL_BASELINE":
        base_risk += 15.0

    calculated_risk = max(5.0, min(95.0, base_risk)) if (failed_rules > 0 or not cert_compliant) else (
        12.0 if best_anchor == "NIST_PQC_TRANSITIONAL" else 8.0 if best_anchor == "CNSA_2_0" else 22.0
    )

    return {
        "session_id": session_id,
        "src_ip": src_ip,
        "dst_ip": dst_ip,
        "ike_version": ike_version,
        "ipsec_mode": ipsec_mode,
        "rfc_status": rfc_status,
        "pqc_class": pqc_class,
        "hybrid_class": hybrid_class,
        "crypto_posture": crypto_posture,
        "passed_rules": passed_rules,
        "failed_rules": failed_rules,
        "warning_rules": warning_rules,
        "total_evaluated": total_evaluated,
        "best_anchor": best_anchor,
        "anchor_display": anchor_display,
        "similarity_score": similarity_score,
        "similarity_pct": similarity_pct,
        "cosine_distance": cosine_distance,
        "rankings": rankings,
        "cert_status": cert_status,
        "cert_compliant": cert_compliant,
        "total_certs": total_certs,
        "peers": peers,
        "packet_count": packet_count,
        "total_bytes": total_bytes,
        "mean_pkt_size": mean_pkt_size,
        "flow_verdict": flow_verdict,
        "estimated_risk_score": calculated_risk,
    }


def prepare_context_payload(loaded: dict[str, Any], compact: bool = False) -> dict[str, Any]:
    """Condense or serialize JSON outputs to optimize token budget while retaining 100% analytical fidelity."""
    if not compact:
        full_payload = {}
        for k in ["canonical_session", "rfc_compliance", "vector_posture", "cert_health", "traffic_flow"]:
            if loaded.get(k):
                full_payload[k] = loaded[k]
        return full_payload

    # Compact mode: summarize passed rules while preserving critical failures, warnings, certs, and vectors
    compact_payload: dict[str, Any] = {}

    # 1. Canonical Session
    canon = loaded.get("canonical_session")
    if canon:
        compact_payload["canonical_session"] = {
            "session_id": canon.get("session_id"),
            "ipsec_mode": canon.get("ipsec_mode"),
            "common": canon.get("common"),
            "IKE_SA_INIT_transforms": [
                p.get("transforms") for p in canon.get("IKE_SA_INIT", {}).get("proposals", [])
            ],
            "IKE_AUTH": canon.get("IKE_AUTH"),
        }

    # 2. RFC Compliance (preserve all failures, warnings, categories, and rule summaries)
    rfc = loaded.get("rfc_compliance")
    if rfc:
        compact_payload["rfc_compliance"] = {
            "overall_rfc_status": rfc.get("overall_rfc_status"),
            "pqc_classification": rfc.get("pqc_classification"),
            "hybrid_classification": rfc.get("hybrid_classification"),
            "cryptographic_posture": rfc.get("cryptographic_posture"),
            "counts": rfc.get("counts"),
            "category_summaries": rfc.get("category_summaries"),
            "critical_failures": rfc.get("critical_failures", []),
            "warnings": rfc.get("warnings", []),
            "not_verifiable_rules": rfc.get("not_verifiable_rules", []),
            "passed_rules_overview": [
                {"rule_id": r.get("rule_id"), "condition": r.get("condition")}
                for r in rfc.get("passed_rules", [])[:15]
            ],
        }

    # 3. Vector Posture
    if loaded.get("vector_posture"):
        compact_payload["vector_posture"] = loaded["vector_posture"]

    # 4. PKI Health
    cert = loaded.get("cert_health")
    if cert:
        compact_payload["cert_health"] = {
            "overall_health_status": cert.get("overall_health_status"),
            "is_compliant": cert.get("is_compliant"),
            "summary": cert.get("summary"),
            "peers": cert.get("peers") or cert.get("peer_audits"),
            "findings": cert.get("findings", []),
            "remediation_actions": cert.get("remediation_actions", []),
        }

    # 5. Traffic Flow
    if loaded.get("traffic_flow"):
        compact_payload["traffic_flow"] = loaded["traffic_flow"]

    return compact_payload


def build_groq_prompts(
    loaded: dict[str, Any],
    metrics: dict[str, Any],
    file_metadata: list[dict[str, Any]],
    compact: bool = False,
) -> tuple[str, str]:
    """Construct elite-tier system and user prompts to drive comprehensive Groq report generation."""

    system_prompt = (
        "You are an elite Principal Cybersecurity Architect, Quantum Cryptographer, and "
        "IETF RFC Compliance Auditor specializing in IKEv2 (RFC 7296, RFC 8247, RFC 9395), "
        "Post-Quantum Cryptography (RFC 9370, NIST FIPS 203/204/205, NSA CNSA 2.0), "
        "X.509 PKI architecture, and IPsec ESP traffic engineering. "
        "Your task is to analyze empirical session data generated by the Enterprise Rule Engine "
        "and produce a publication-grade, deeply technical and executive security evaluation report. "
        "You must explain exactly how identified weaknesses or deprecations can be weaponized into threats, "
        "provide clear quantitative metrics, generate a comprehensive Threat Matrix, and embed renderable Mermaid.js diagrams. "
        "Do NOT mention or include any hackathon, competition, or problem statement keywords in your response."
    )

    payload_dict = prepare_context_payload(loaded, compact=compact)

    user_prompt = f"""# MISSION: Generate Comprehensive Executive & Technical Security Audit Report

You are auditing an empirical IKEv2 / IPsec session evaluated across multiple automated analytical engines.
All session JSON artifacts produced during testing have been collected and are provided below.

---

## 1. EVALUATION TARGET & METRICS OVERVIEW
- **Session Identifier (SPI)**: `{metrics['session_id']}`
- **Peer Endpoints**: `{metrics['src_ip']}` (Initiator) <---> `{metrics['dst_ip']}` (Responder)
- **Protocol & Mode**: IKEv2 (Version {metrics['ike_version']}) | IPsec Mode: `{metrics['ipsec_mode']}`
- **RFC Compliance Status**: `{metrics['rfc_status']}` (Passed: {metrics['passed_rules']}, Failures: {metrics['failed_rules']}, Warnings: {metrics['warning_rules']}, Total Evaluated: {metrics['total_evaluated']})
- **Cryptographic Posture & Vector**: `{metrics['crypto_posture']}` | Closest Anchor: `{metrics['anchor_display']}` ({metrics['similarity_pct']} similarity, cosine distance: {metrics['cosine_distance']})
- **Post-Quantum Cryptography Classification**: `{metrics['pqc_class']}` | Hybrid Status: `{metrics['hybrid_class']}`
- **X.509 PKI Health**: `{metrics['cert_status']}` | Compliant: `{metrics['cert_compliant']}` | Audited Certificates: {metrics['total_certs']}
- **ESP Data-Plane Telemetry**: {metrics['packet_count']} packets | {metrics['total_bytes']} bytes | Mean packet size: {metrics['mean_pkt_size']} bytes | Verdict: `{metrics['flow_verdict']}`

---

## 2. INGESTED SESSION TEST DATA (JSON ARTIFACTS)
```json
{json.dumps(payload_dict, indent=2)}
```

---

## 3. REPORT STRUCTURAL REQUIREMENTS
Generate a comprehensive, beautifully structured report in GitHub Flavored Markdown adhering strictly to the following sections:

### Title & Header
- Professional Header with Security Classification (e.g. `CONFIDENTIAL // AUDIT EVALUATION REPORT`)
- Session Metadata Table (Session ID, Source/Destination IPs, Evaluation Date, Audit Framework: Enterprise Cryptographic Rule Engine)

### Section 1: Executive Summary & C-Suite Briefing
- High-level executive overview written for CISOs, CTOs, and Security Directors.
- State of Security Posture: Is the connection secure against classical threats? Is it quantum-resistant?
- Bottom-Line Business & Operational Risk.
- Executive Bullet Points summarizing the top 3-5 critical takeaways.

### Section 2: Composite Risk Score & Qualitative Risk Meter
- **Quantitative Risk Score**: Provide an authoritative score from **0 to 100** (where 0 = impenetrable/quantum-safe, 100 = active catastrophic compromise).
- **Risk Level**: Designate one of: `[LOW RISK | 0-25]`, `[MODERATE RISK | 26-50]`, `[HIGH RISK | 51-75]`, or `[CRITICAL RISK | 76-100]`.
- Provide a visual Markdown progress meter (e.g. `[████░░░░░░░░░░░░░░░░] 20/100`).
- **Domain Risk Breakdown Table**:
  | Risk Domain | Assessed Score (0-100) | Severity | Primary Contributing Factors |
  | --- | --- | --- | --- |
  (Break down: Control-Plane RFC Adherence, Cryptographic Cipher Strength, Post-Quantum Readiness, PKI / Identity Trust, Data-Plane Anti-Replay).

### Section 3: AI Confidence Score & Diagnostic Telemetry
- **Composite AI Confidence Score**: (e.g. `98.5%`).
- **Domain-Level Confidence Breakdown**:
  - RFC Engine Verification Confidence
  - 19-Dimensional Cryptographic Vector Mapping Confidence
  - PKI / X.509 Chain Validation Confidence
  - ESP Traffic Flow Classification Confidence
- **Audit Coverage & Verification Depth**: Percentage of RFC rules successfully verified vs. non-verifiable.

### Section 4: Comprehensive Multi-Vector Threat Matrix
Construct a detailed Markdown table analyzing potential threats to this session:
| Threat ID | Threat Vector / Attack Scenario | Category | Exploitability | Impact | Affected Layer / RFC Reference | Status (Mitigated / Latent / Active) | Recommended Countermeasure |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
*(Include at least 5 distinct threat vectors: Harvest Now Decrypt Later, Man-in-the-Middle Downgrade, Replay Attack, Rogue Identity/Impersonation, Traffic Fingerprinting / Side-Channel).*

### Section 5: Deep-Dive Technical Audit
Provide meticulous technical commentary on the following 5 domains:
1. **IKEv2 Control-Plane Protocol & Transform Negotiation**:
   - RFC 7296 and RFC 9395 adherence.
   - Evaluated transforms (Encryption, PRF, Integrity, DH Groups, ESN).
   - Analysis of passed rules and any non-verifiable rules.
2. **19-Dimensional Cryptographic Vector & Policy Anchor Alignment**:
   - Cosine similarity analysis against NIST PQC Transitional, CNSA 2.0, RFC 8247, and NIST SP 800-131A.
   - Exact mathematical distance interpretation.
3. **Post-Quantum Cryptography (PQC) & Hybrid Key Exchange**:
   - RFC 9370 Multi-KE evaluation.
   - KEM algorithms (ML-KEM-1024, Kyber), Classical DH (P-384 / Group 20), and Hybrid Binding robustness.
   - Resistance against Shor's algorithm and quantum cryptanalysis.
4. **X.509 PKI & Identity Verification**:
   - Certificate chain health, key types (e.g. ML-DSA-87 / Dilithium / RSA), signature algorithms, validity periods, Subject Alternative Names (SAN), and CA hierarchy.
   - Compliance with CNSA 2.0 mandate.
5. **ESP Data-Plane Traffic Flow & Anti-Replay Telemetry**:
   - Packet count, packet size distribution, throughput, and 64-packet sliding window anti-replay behavior.

### Section 6: Threat Mechanics: How Identified Vectors Can Become Active Exploits
**Crucial Requirement**: For each potential vulnerability or architectural weakness (e.g. Harvest Now Decrypt Later, algorithm downgrade, missing ESN, legacy fallback, certificate expiration), explain step-by-step:
1. **The Attacker's Perspective**: What resources, access, or positioning does the adversary need?
2. **The Weaponization Chain**: How does the exploit unfold sequentially?
3. **The Real-World Impact**: What data, keys, or systems are compromised?

### Section 7: Architectural, Sequence & Threat Model Diagrams (Mermaid.js)
Generate at least THREE valid, renderable Mermaid.js diagrams enclosed in ```mermaid code blocks:
1. **Diagram 1 (Sequence Diagram)**: Complete IKEv2 Handshake Sequence (IKE_SA_INIT, RFC 9370 IKE_INTERMEDIATE multi-KE, IKE_AUTH, and ESP Child SA activation) showing SPIs, nonces, key exchanges, and transforms.
2. **Diagram 2 (Graph / Trust Chain)**: PKI Certificate Hierarchy and Identity Verification flow.
3. **Diagram 3 (Threat Surface Model)**: Architectural Defense-in-Depth and Threat Boundary mapping.

### Section 8: Prioritized Remediation Roadmap & Hardening Guidelines
- **Phase 1: Immediate Actions (P0 - Next 24-48 Hours)**: Critical fixes if any, or verification milestones.
- **Phase 2: Short-Term Hardening (P1 - 30 Days)**: Configuration tweaks and cipher pruning.
- **Phase 3: Strategic Post-Quantum Migration (P2 - 6-12 Months)**: CNSA 2.0 full transition plan.
- **Concrete Configuration Snippet**: Provide a production-ready strongSwan `swanctl.conf` or Cisco IPsec configuration representing the hardened target posture.

Do not use any competition, hackathon, or problem statement numbers/acronyms anywhere in the report.
"""

    return system_prompt, user_prompt


def generate_mock_report(metrics: dict[str, Any]) -> str:
    """Generate a high-fidelity synthetic report for offline validation (--dry-run)."""
    return f"""# CONFIDENTIAL // AUDIT EVALUATION REPORT
**Enterprise Quantum-Safe IPsec & IKEv2 Compliance Engine**

| Parameter | Observed Value |
| :--- | :--- |
| **Session SPI** | `{metrics['session_id']}` |
| **Initiator Endpoint** | `{metrics['src_ip']}` |
| **Responder Endpoint** | `{metrics['dst_ip']}` |
| **Protocol Mode** | IKEv2 (Tunnel Mode) |
| **Audit Status** | `{metrics['rfc_status']}` |
| **Cryptographic Posture** | `{metrics['crypto_posture']}` ({metrics['anchor_display']}) |
| **Evaluation Date** | {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")} |

---

## 1. Executive Summary & C-Suite Briefing
This cryptographic security audit evaluates the active IPsec / IKEv2 session `{metrics['session_id']}` negotiated between `{metrics['src_ip']}` and `{metrics['dst_ip']}`. The target connection has been analyzed across four autonomous analytical layers: control-plane RFC compliance (RFC 7296, RFC 8247, RFC 9395), 19-dimensional cryptographic vector alignment, X.509 PKI health, and sliding-window ESP data-plane telemetry.

> [!NOTE]
> The assessed session demonstrates an exceptionally robust security posture adhering to modern Post-Quantum Cryptography (PQC) standards and NIST Transitional mandates.

### Key Executive Takeaways:
- **Quantum Resistance**: The session implements **RFC 9370 Multi-KE** utilizing **ML-KEM-1024** bound with classical P-384 Diffie-Hellman, effectively neutralizing "Harvest Now, Decrypt Later" (HNDL) attacks.
- **Authentication Strength**: Peer identity is authenticated using **ML-DSA-87** (Dilithium5) quantum-resilient signatures, satisfying NSA CNSA 2.0 Category 5 requirements.
- **Data-Plane Integrity**: The Child SA employs **AES-GCM-256** AEAD encryption with Extended Sequence Numbers (ESN) and an active 64-packet anti-replay window.

---

## 2. Composite Risk Score & Qualitative Risk Meter

**Assessed Risk Score**: **{metrics['estimated_risk_score']:.0f} / 100** &mdash; `[LOW RISK | 0-25]`
```text
[███░░░░░░░░░░░░░░░░░] {metrics['estimated_risk_score']:.0f}/100 — Resilient Quantum-Safe Posture
```

### Domain Risk Breakdown Table
| Risk Domain | Assessed Score (0-100) | Severity | Primary Contributing Factors |
| :--- | :--- | :--- | :--- |
| **Control-Plane RFC Adherence** | 5 / 100 | LOW | 23/23 applicable rules verified passing; zero RFC 9395 deprecated transforms. |
| **Cryptographic Cipher Strength** | 8 / 100 | LOW | AES-GCM-256 with HMAC-SHA2-384 PRF; aligns 97.78% with NIST PQC Transitional profile. |
| **Post-Quantum Readiness** | 10 / 100 | LOW | ML-KEM-1024 KEM and ML-DSA-87 signatures deployed; hybrid classical binding active. |
| **PKI & Identity Trust** | 12 / 100 | LOW | Active leaf certificates with 365 days validity; valid SAN matching client identity. |
| **Data-Plane Anti-Replay** | 6 / 100 | LOW | ESN negotiated; zero out-of-order sequence packet replay flags observed in ESP flow. |

---

## 3. AI Confidence Score & Diagnostic Telemetry

- **Composite AI Confidence Score**: **98.4%**
- **Verification Coverage**: 100% of verifiable control-plane and data-plane rules satisfied.

| Analytical Engine | Confidence Rating | Data Completeness | Diagnostic Verdict |
| :--- | :--- | :--- | :--- |
| **RFC Compliance Engine** | 99.1% | Complete Handshake Captured | All mandatory transforms present |
| **19-D Vector Engine** | 98.7% | 19/19 Dimensions Populated | Cosine similarity: 0.9778 |
| **PKI Health Engine** | 97.9% | End-Entity Chains Validated | CNSA 2.0 compliant (ML-DSA-87) |
| **Flow Telemetry Engine** | 98.0% | 250 packets / 185 KB | Sliding window anti-replay active |

---

## 4. Comprehensive Multi-Vector Threat Matrix

| Threat ID | Threat Vector / Attack Scenario | Category | Exploitability | Impact | Affected Layer / RFC Reference | Status | Recommended Countermeasure |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| **THR-001** | Harvest Now, Decrypt Later (HNDL) | Quantum Cryptanalysis | Low | Critical | RFC 9370 / NIST FIPS 203 | **MITIGATED** | Hybrid ML-KEM-1024 + P-384 active |
| **THR-002** | IKE_SA_INIT Transform Downgrade | Man-in-the-Middle | Low | High | RFC 7296 Section 3.3 | **MITIGATED** | Strict proposal enforcement |
| **THR-003** | Sequence Number Replay / Injection | Data Plane Replay | Low | High | RFC 4303 / RFC 4304 | **MITIGATED** | ESN 64-bit + 64-packet window |
| **THR-004** | Rogue Gateway Identity Impersonation | PKI / Spoofing | Very Low | Critical | RFC 7296 / X.509 PKI | **MITIGATED** | ML-DSA-87 leaf cert + SAN match |
| **THR-005** | Traffic Flow Analysis & Packet Size Leaks| Side-Channel | Medium | Low | ESP Data Plane Telemetry | **MONITORED** | ESP padding / traffic masking |

---

## 5. Deep-Dive Technical Audit

### 5.1 IKEv2 Protocol & Handshake Compliance
The control-plane exchange strictly complies with **RFC 7296** and eliminates all legacy constructs deprecated by **RFC 9395**.
- **Encryption Transform**: AES-GCM with 256-bit key (Transform ID 20, 16-octet ICV).
- **Pseudo-Random Function (PRF)**: HMAC-SHA2-384 (Transform ID 6).
- **Integrity Transform**: None explicitly required due to AEAD cipher mode.
- **Diffie-Hellman Group**: 384-bit random ECP group (Group ID 20).
- **Additional Key Exchange**: RFC 9370 Additional Key Exchange 1 (Transform ID 37: ML-KEM-1024).

### 5.2 19-Dimensional Cryptographic Vector Analysis
The vector engine scored the session across 19 orthogonal cryptographic dimensions.
- **Closest Anchor**: `NIST_PQC_TRANSITIONAL` (Cosine Distance: `0.0222`, Similarity: `97.78%`)
- **Secondary Anchor**: `CNSA_2_0` (Cosine Distance: `0.0287`, Similarity: `97.13%`)
- **Classical Baseline**: `RFC8247_CLASSICAL_BASELINE` (Cosine Distance: `0.2071`, Similarity: `79.29%`)
- **Deprecated Profile**: `NIST_SP800_131A_DEPRECATED` (Cosine Distance: `0.5694`, Similarity: `43.06%`)

### 5.3 X.509 PKI Health Audit
Both Initiator and Responder identities were validated through X.509 credentials:
- **Leaf Signature Algorithm**: `ML-DSA-87` (OID `2.16.840.1.101.3.4.3.19`), 2592 bits key length.
- **Validity Window**: Active, 365 days remaining until expiration.
- **Identity SAN**: Successfully matched peer FQDN `client.quantum.enterprise.net`.

---

## 6. Threat Mechanics: How Identified Vectors Can Become Active Exploits

### 6.1 "Harvest Now, Decrypt Later" (HNDL)
* **The Attacker's Perspective**: Nation-state or sophisticated threat actors passively record encrypted IPsec ciphertext over transit networks and store it until cryptanalytically relevant quantum computers (CRQCs) running Shor's algorithm become viable.
* **The Weaponization Chain**: An adversary intercepting classical Diffie-Hellman exchanges (e.g. Group 14 MODP or P-256) could retroactively solve the discrete logarithm problem, derive the session key `SKEYSEED`, decrypt all historical ESP traffic, and extract classified application data.
* **Mitigation Evaluated**: The session successfully mitigates this attack via **ML-KEM-1024**, which is based on the Module Learning with Errors (M-LWE) lattice problem, impenetrable to both classical and quantum algorithms.

---

## 7. Architectural, Sequence & Threat Model Diagrams

### Diagram 1: IKEv2 Hybrid Post-Quantum Handshake Sequence
```mermaid
sequenceDiagram
    autonumber
    participant Init as Initiator (192.168.10.50)
    participant Resp as Responder (10.0.0.1)

    Note over Init,Resp: IKE_SA_INIT (Exchange 34)
    Init->>Resp: HDR, SAi1 (AES-GCM-256, PRF-SHA384, DH-P384, ESN), Ni, KEi (P-384)
    Resp->>Init: HDR, SAr1 (Selected Transforms), Nr, KEr (P-384), CERTREQ

    Note over Init,Resp: IKE_INTERMEDIATE (RFC 9370 Multi-KE)
    Init->>Resp: HDR, SK {{ KEi1 (ML-KEM-1024 Public Key) }}
    Resp->>Init: HDR, SK {{ KEr1 (ML-KEM-1024 Ciphertext) }}

    Note over Init,Resp: SKEYSEED Derived with Hybrid Classical + PQC Binding
    Note over Init,Resp: IKE_AUTH (Exchange 35)
    Init->>Resp: HDR, SK {{ IDi, CERT (ML-DSA-87), AUTH, SAi2 (ESP AES-GCM-256) }}
    Resp->>Init: HDR, SK {{ IDr, CERT (ML-DSA-87), AUTH, SAr2 (ESP AES-GCM-256) }}

    Note over Init,Resp: ESP IPsec Tunnel Established (Anti-Replay Window: 64 pkts)
```

### Diagram 2: PKI Hierarchy & Quantum Verification Chain
```mermaid
graph TD
    RootCA["Enterprise Post-Quantum Root CA<br/>(ML-DSA-87 / NIST Category 5)"]
    InterCA["Quantum Enterprise Intermediate CA<br/>(ML-DSA-87 / Valid)"]
    LeafInit["Initiator Leaf Cert<br/>CN=client.quantum.enterprise.net<br/>ML-DSA-87 (2592-bit)"]
    LeafResp["Responder Leaf Cert<br/>CN=gateway.quantum.enterprise.net<br/>ML-DSA-87 (2592-bit)"]

    RootCA --> InterCA
    InterCA --> LeafInit
    InterCA --> LeafResp

    classDef healthy fill:#064e3b,stroke:#10b981,stroke-width:2px,color:#ecfdf5;
    class RootCA,InterCA,LeafInit,LeafResp healthy;
```

### Diagram 3: Threat Surface & Defense-in-Depth Model
```mermaid
flowchart LR
    subgraph Untrusted Network
        ATTACKER["Adversary Position<br/>(Man-in-the-Middle / Tap)"]
    end

    subgraph Defense Boundaries
        PQC["RFC 9370 Multi-KE<br/>ML-KEM-1024<br/>(HNDL Defense)"]
        AEAD["AES-GCM-256<br/>AEAD Encryption<br/>(Tamper Proof)"]
        AUTH["ML-DSA-87<br/>Digital Signature<br/>(Anti-Impersonation)"]
        ESN["64-bit ESN<br/>64-packet Window<br/>(Anti-Replay)"]
    end

    ATTACKER -.->|HNDL Recording| PQC
    ATTACKER -.->|Packet Injection| AEAD
    ATTACKER -.->|Rogue Handshake| AUTH
    ATTACKER -.->|Replayed ESP| ESN
```

---

## 8. Prioritized Remediation Roadmap & Hardening Guidelines

### Phase 1: Immediate Verification (P0 - Next 24-48 Hours)
- Validate that all strongSwan endpoints enforce `ike = aes256gcm16-prfsha384-ecp384-mlkem1024!`.
- Ensure anti-replay windows are active on all security gateways.

### Phase 2: Configuration Hardening (P1 - 30 Days)
- Prune legacy fallback transform proposals to prevent downgrade attempts.
- Enforce mandatory Subject Alternative Name (SAN) validation in peer configuration.

### Phase 3: Strategic CNSA 2.0 Full Migration (P2 - 6-12 Months)
- Complete migration of intermediate CAs to ML-DSA-87 in accordance with the NSA CNSA 2.0 timeline.

### Hardened strongSwan `swanctl.conf` Snippet
```ini
connections {{
    pqc-enterprise-tunnel {{
        version = 2
        local_addrs = 192.168.10.50
        remote_addrs = 10.0.0.1
        proposals = aes256gcm16-prfsha384-ecp384-mlkem1024
        
        local {{
            auth = pubkey
            certs = client-mldsa87.crt
            id = client.quantum.enterprise.net
        }}
        remote {{
            auth = pubkey
            id = gateway.quantum.enterprise.net
        }}
        
        children {{
            net-tunnel {{
                esp_proposals = aes256gcm16-esn
                mode = tunnel
                rekey_time = 1h
            }}
        }}
    }}
}}
```
"""


def generate_html_report(
    markdown_content: str,
    metrics: dict[str, Any],
    report_title: str,
    generation_time: str,
    model_name: str,
) -> str:
    """Render an ultra-high-contrast, executive-grade standalone HTML report with Light/Dark toggle."""

    risk_score = metrics.get("estimated_risk_score", 12.0)
    if risk_score <= 25:
        risk_label = "LOW RISK"
        risk_badge_class = "badge-low"
    elif risk_score <= 50:
        risk_label = "MODERATE"
        risk_badge_class = "badge-mod"
    elif risk_score <= 75:
        risk_label = "HIGH RISK"
        risk_badge_class = "badge-high"
    else:
        risk_label = "CRITICAL"
        risk_badge_class = "badge-crit"

    rfc_status = metrics.get("rfc_status", "PASS")
    escaped_markdown = json.dumps(markdown_content)

    html_template = f"""<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{report_title} | Enterprise Security Audit</title>
  <!-- Google Fonts: Inter & JetBrains Mono -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600;700&display=swap" rel="stylesheet">
  
  <!-- Marked.js (Markdown parsing) & Mermaid.js (Diagrams) -->
  <script src="https://cdn.jsdelivr.net/npm/marked@12.0.1/marked.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10.9.0/dist/mermaid.min.js"></script>

  <style>
    /* =====================================================================
       HIGH-CONTRAST DESIGN SYSTEM (LIGHT THEME DEFAULT & DARK THEME TOGGLE)
       ===================================================================== */
    :root, html[data-theme="light"] {{
      --bg-page: #f1f5f9;
      --bg-card: #ffffff;
      --bg-card-subtle: #f8fafc;
      --border-strong: #94a3b8;
      --border-subtle: #cbd5e1;
      --text-main: #020617;          /* WCAG AAA Max Contrast (Near Black) */
      --text-sub: #1e293b;           /* Legible Slate-800 */
      --text-muted: #475569;         /* Slate-600 */
      
      --accent-primary: #0284c7;     /* High-Visibility Ocean Blue */
      --accent-primary-text: #ffffff;
      --accent-hover: #0369a1;
      
      /* Badges & Status */
      --status-pass-bg: #dcfce7;
      --status-pass-border: #15803d;
      --status-pass-text: #14532d;
      
      --status-warn-bg: #fef3c7;
      --status-warn-border: #b45309;
      --status-warn-text: #78350f;
      
      --status-fail-bg: #fee2e2;
      --status-fail-border: #b91c1c;
      --status-fail-text: #7f1d1d;
      
      --status-blue-bg: #e0f2fe;
      --status-blue-border: #0369a1;
      --status-blue-text: #075985;

      --table-header-bg: #0f172a;
      --table-header-text: #ffffff;
      --table-row-alt: #f8fafc;
      --table-border: #cbd5e1;
      
      --code-block-bg: #0f172a;
      --code-block-text: #f8fafc;
      --inline-code-bg: #e2e8f0;
      --inline-code-text: #0f172a;

      --shadow-sm: 0 1px 3px rgba(0, 0, 0, 0.1);
      --shadow-md: 0 4px 12px -2px rgba(0, 0, 0, 0.12), 0 2px 6px -2px rgba(0, 0, 0, 0.08);
      --shadow-lg: 0 10px 25px -5px rgba(0, 0, 0, 0.15);
    }}

    html[data-theme="dark"] {{
      --bg-page: #030712;            /* Deep Pitch Black for Pure Contrast */
      --bg-card: #0f172a;            /* Solid Dark Slate */
      --bg-card-subtle: #1e293b;
      --border-strong: #475569;
      --border-subtle: #334155;
      --text-main: #ffffff;          /* Pure White */
      --text-sub: #e2e8f0;           /* Crisp Light Slate */
      --text-muted: #94a3b8;
      
      --accent-primary: #38bdf8;
      --accent-primary-text: #020617;
      --accent-hover: #7dd3fc;
      
      --status-pass-bg: #064e3b;
      --status-pass-border: #10b981;
      --status-pass-text: #ecfdf5;
      
      --status-warn-bg: #78350f;
      --status-warn-border: #f59e0b;
      --status-warn-text: #fffbeb;
      
      --status-fail-bg: #7f1d1d;
      --status-fail-border: #ef4444;
      --status-fail-text: #fef2f2;
      
      --status-blue-bg: #0c4a6e;
      --status-blue-border: #38bdf8;
      --status-blue-text: #e0f2fe;

      --table-header-bg: #1e293b;
      --table-header-text: #ffffff;
      --table-row-alt: #0b1120;
      --table-border: #334155;
      
      --code-block-bg: #020617;
      --code-block-text: #f8fafc;
      --inline-code-bg: #1e293b;
      --inline-code-text: #38bdf8;

      --shadow-sm: 0 1px 3px rgba(0, 0, 0, 0.5);
      --shadow-md: 0 4px 14px rgba(0, 0, 0, 0.6);
      --shadow-lg: 0 15px 35px rgba(0, 0, 0, 0.7);
    }}

    * {{ box-sizing: border-box; margin: 0; padding: 0; }}

    body {{
      background-color: var(--bg-page);
      color: var(--text-main);
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.65;
      padding: 2rem 1rem;
      transition: background-color 0.25s ease, color 0.25s ease;
    }}

    .container {{
      max-width: 1200px;
      margin: 0 auto;
    }}

    /* Header Banner */
    .header-banner {{
      background: var(--bg-card);
      border: 2px solid var(--border-subtle);
      border-radius: 14px;
      padding: 2rem;
      margin-bottom: 2rem;
      box-shadow: var(--shadow-md);
      position: relative;
    }}

    .header-banner::before {{
      content: '';
      position: absolute;
      top: 0; left: 0; right: 0;
      height: 4px;
      background: linear-gradient(90deg, #0284c7, #2563eb, #059669);
      border-radius: 12px 12px 0 0;
    }}

    .header-top {{
      display: flex;
      justify-content: space-between;
      align-items: center;
      flex-wrap: wrap;
      gap: 1rem;
      margin-bottom: 1.25rem;
    }}

    .classification-tag {{
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      font-size: 0.78rem;
      font-weight: 800;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      padding: 0.35rem 0.85rem;
      border-radius: 6px;
      background: var(--status-blue-bg);
      color: var(--status-blue-text);
      border: 1.5px solid var(--status-blue-border);
    }}

    .action-bar {{
      display: flex;
      gap: 0.65rem;
      align-items: center;
    }}

    .btn {{
      display: inline-flex;
      align-items: center;
      gap: 0.5rem;
      font-size: 0.85rem;
      font-weight: 700;
      padding: 0.55rem 1rem;
      border-radius: 8px;
      cursor: pointer;
      transition: all 0.2s ease;
      text-decoration: none;
      border: 1.5px solid var(--border-strong);
      background: var(--bg-card-subtle);
      color: var(--text-main);
    }}

    .btn:hover {{
      border-color: var(--accent-primary);
      transform: translateY(-1px);
      box-shadow: var(--shadow-sm);
    }}

    .btn-primary {{
      background: var(--accent-primary);
      color: var(--accent-primary-text);
      border: 1.5px solid var(--accent-primary);
    }}

    .btn-primary:hover {{
      background: var(--accent-hover);
    }}

    .title-block h1 {{
      font-size: 2.1rem;
      font-weight: 800;
      letter-spacing: -0.025em;
      color: var(--text-main);
      margin-bottom: 0.4rem;
    }}

    .title-block p {{
      color: var(--text-muted);
      font-size: 0.95rem;
      font-weight: 500;
    }}

    /* Metric Grid Cards (High-Contrast) */
    .metric-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(210px, 1fr));
      gap: 1.25rem;
      margin-bottom: 2rem;
    }}

    .metric-card {{
      background: var(--bg-card);
      border: 2px solid var(--border-subtle);
      border-radius: 12px;
      padding: 1.25rem;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      box-shadow: var(--shadow-sm);
      transition: transform 0.2s ease, border-color 0.2s ease;
    }}

    .metric-card:hover {{
      transform: translateY(-2px);
      border-color: var(--accent-primary);
      box-shadow: var(--shadow-md);
    }}

    .metric-label {{
      font-size: 0.75rem;
      font-weight: 800;
      text-transform: uppercase;
      letter-spacing: 0.06em;
      color: var(--text-muted);
      margin-bottom: 0.5rem;
    }}

    .metric-value {{
      font-size: 1.7rem;
      font-weight: 800;
      font-family: 'JetBrains Mono', monospace;
      color: var(--text-main);
      display: flex;
      align-items: baseline;
      gap: 0.35rem;
    }}

    .metric-subtext {{
      font-size: 0.82rem;
      font-weight: 600;
      color: var(--text-sub);
      margin-top: 0.6rem;
    }}

    /* Badges */
    .badge {{
      display: inline-block;
      padding: 0.22rem 0.65rem;
      border-radius: 6px;
      font-size: 0.76rem;
      font-weight: 800;
      font-family: 'JetBrains Mono', monospace;
      text-transform: uppercase;
      letter-spacing: 0.04em;
    }}
    .badge-low {{ background: var(--status-pass-bg); color: var(--status-pass-text); border: 1.5px solid var(--status-pass-border); }}
    .badge-mod {{ background: var(--status-warn-bg); color: var(--status-warn-text); border: 1.5px solid var(--status-warn-border); }}
    .badge-high {{ background: var(--status-warn-bg); color: var(--status-warn-text); border: 1.5px solid var(--status-warn-border); }}
    .badge-crit {{ background: var(--status-fail-bg); color: var(--status-fail-text); border: 1.5px solid var(--status-fail-border); }}
    .badge-blue {{ background: var(--status-blue-bg); color: var(--status-blue-text); border: 1.5px solid var(--status-blue-border); }}

    /* Report Card & Typography */
    .report-card {{
      background: var(--bg-card);
      border: 2px solid var(--border-subtle);
      border-radius: 14px;
      padding: 2.75rem;
      box-shadow: var(--shadow-lg);
    }}

    .markdown-body h1, .markdown-body h2, .markdown-body h3, .markdown-body h4 {{
      color: var(--text-main);
      font-weight: 800;
      margin-top: 2rem;
      margin-bottom: 1rem;
      letter-spacing: -0.02em;
    }}
    .markdown-body h1 {{
      font-size: 1.85rem;
      border-bottom: 2px solid var(--border-subtle);
      padding-bottom: 0.75rem;
    }}
    .markdown-body h2 {{
      font-size: 1.45rem;
      border-bottom: 1.5px solid var(--border-subtle);
      padding-bottom: 0.5rem;
      color: var(--text-main);
    }}
    .markdown-body h3 {{ font-size: 1.2rem; }}

    .markdown-body p, .markdown-body li {{
      color: var(--text-sub);
      font-size: 1rem;
      line-height: 1.7;
      margin-bottom: 1rem;
    }}

    .markdown-body strong {{
      color: var(--text-main);
      font-weight: 700;
    }}

    .markdown-body ul, .markdown-body ol {{
      padding-left: 1.75rem;
      margin-bottom: 1.25rem;
    }}

    /* High-Contrast Tables */
    .markdown-body table {{
      width: 100%;
      border-collapse: collapse;
      margin: 1.75rem 0;
      font-size: 0.92rem;
      background: var(--bg-card);
      border-radius: 8px;
      overflow: hidden;
      border: 2px solid var(--table-border);
      box-shadow: var(--shadow-sm);
    }}

    .markdown-body th {{
      background: var(--table-header-bg);
      color: var(--table-header-text);
      text-align: left;
      padding: 0.9rem 1rem;
      font-weight: 800;
      font-size: 0.82rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      border: 1px solid var(--table-border);
    }}

    .markdown-body td {{
      padding: 0.85rem 1rem;
      border: 1px solid var(--table-border);
      color: var(--text-main);
      vertical-align: middle;
    }}

    .markdown-body tr:nth-child(even) td {{
      background: var(--table-row-alt);
    }}

    .markdown-body tr:hover td {{
      background: rgba(2, 132, 199, 0.08);
    }}

    /* Code Blocks */
    .markdown-body code {{
      font-family: 'JetBrains Mono', monospace;
      background: var(--inline-code-bg);
      color: var(--inline-code-text);
      padding: 0.2rem 0.45rem;
      border-radius: 5px;
      font-size: 0.88em;
      font-weight: 600;
    }}

    .markdown-body pre {{
      background: var(--code-block-bg) !important;
      border: 2px solid var(--border-strong);
      border-radius: 10px;
      padding: 1.25rem;
      overflow-x: auto;
      margin: 1.5rem 0;
      box-shadow: var(--shadow-md);
    }}

    .markdown-body pre code {{
      background: transparent;
      padding: 0;
      font-size: 0.9rem;
      color: var(--code-block-text);
      font-weight: 500;
    }}

    .markdown-body blockquote {{
      border-left: 5px solid var(--accent-primary);
      padding: 0.85rem 1.25rem;
      margin: 1.5rem 0;
      background: var(--status-blue-bg);
      color: var(--text-main);
      border-radius: 0 8px 8px 0;
      font-weight: 500;
    }}

    /* Mermaid Diagrams */
    .mermaid {{
      background: var(--bg-card-subtle);
      border: 2px solid var(--border-subtle);
      border-radius: 12px;
      padding: 1.75rem;
      margin: 2rem 0;
      display: flex;
      justify-content: center;
      overflow-x: auto;
      box-shadow: var(--shadow-sm);
    }}

    footer {{
      margin-top: 3rem;
      text-align: center;
      color: var(--text-muted);
      font-size: 0.85rem;
      font-weight: 600;
      padding: 1.5rem;
    }}

    @media print {{
      body {{ background: white !important; color: black !important; padding: 0; }}
      .header-banner, .metric-card, .report-card {{
        background: white !important;
        box-shadow: none !important;
        border: 1px solid #333 !important;
        color: black !important;
      }}
      .action-bar {{ display: none !important; }}
      .markdown-body th {{ background: #000 !important; color: #fff !important; }}
      .markdown-body td {{ color: #000 !important; }}
    }}
  </style>
</head>
<body>
  <div class="container">
    <!-- Header Banner -->
    <header class="header-banner">
      <div class="header-top">
        <span class="classification-tag">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><path d="M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4z"/></svg>
          Enterprise Cryptographic Audit System
        </span>
        <div class="action-bar">
          <button class="btn" id="theme-toggle-btn" onclick="toggleTheme()">
            <span id="theme-icon">🌙</span> <span id="theme-text">Dark Theme</span>
          </button>
          <button class="btn btn-primary" onclick="window.print()">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M6 9V2h12v7M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2"/><rect x="6" y="14" width="12" height="8"/></svg>
            Print / Save PDF
          </button>
          <button class="btn" onclick="copyMarkdown()">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/></svg>
            Copy Markdown
          </button>
        </div>
      </div>

      <div class="title-block">
        <h1>{report_title}</h1>
        <p>Session ID: <strong style="color:var(--accent-primary); font-family:'JetBrains Mono'">{metrics['session_id']}</strong> &bull; Generated: <strong>{generation_time}</strong> &bull; Engine Model: <strong>{model_name}</strong></p>
      </div>
    </header>

    <!-- Executive Metric Cards -->
    <section class="metric-grid">
      <!-- Card 1: Risk Score -->
      <div class="metric-card">
        <div class="metric-label">Composite Risk Score</div>
        <div class="metric-value">
          {risk_score:.0f}<span style="font-size: 0.9rem; color: var(--text-muted); font-weight:600">/100</span>
        </div>
        <div class="metric-subtext">
          <span class="badge {risk_badge_class}">{risk_label}</span>
        </div>
      </div>

      <!-- Card 2: RFC Status -->
      <div class="metric-card">
        <div class="metric-label">RFC Compliance Status</div>
        <div class="metric-value">
          {rfc_status}
        </div>
        <div class="metric-subtext">
          <strong style="color: #15803d">{metrics['passed_rules']} Passed</strong> &bull; 
          <strong style="color: #b91c1c">{metrics['failed_rules']} Failures</strong>
        </div>
      </div>

      <!-- Card 3: 19-D Vector Alignment -->
      <div class="metric-card">
        <div class="metric-label">19-D Vector Alignment</div>
        <div class="metric-value" style="font-size: 1.4rem;">
          {metrics['similarity_pct']}
        </div>
        <div class="metric-subtext">
          Anchor: <strong>{metrics['best_anchor']}</strong>
        </div>
      </div>

      <!-- Card 4: Post-Quantum Status -->
      <div class="metric-card">
        <div class="metric-label">PQC & Hybrid Posture</div>
        <div class="metric-value" style="font-size: 1.4rem;">
          {metrics['pqc_class']}
        </div>
        <div class="metric-subtext">
          Hybrid: <span class="badge badge-blue">{metrics['hybrid_class']}</span>
        </div>
      </div>

      <!-- Card 5: PKI Health -->
      <div class="metric-card">
        <div class="metric-label">PKI & Certificate Health</div>
        <div class="metric-value" style="font-size: 1.4rem;">
          {metrics['cert_status']}
        </div>
        <div class="metric-subtext">
          Audited: <strong>{metrics['total_certs']} Cert(s)</strong> (CNSA Compliant)
        </div>
      </div>

      <!-- Card 6: Flow Telemetry -->
      <div class="metric-card">
        <div class="metric-label">ESP Traffic Telemetry</div>
        <div class="metric-value" style="font-size: 1.4rem;">
          {metrics['packet_count']} <span style="font-size:0.85rem; color:var(--text-muted)">pkts</span>
        </div>
        <div class="metric-subtext">
          Mean Size: <strong>{metrics['mean_pkt_size']} B</strong> &bull; Verdict: <strong>{metrics['flow_verdict']}</strong>
        </div>
      </div>
    </section>

    <!-- Main Report Body Card -->
    <main class="report-card">
      <div id="report-output" class="markdown-body">
      </div>
    </main>

    <footer>
      Autonomous Quantum-Safe IPsec & IKEv2 Cryptographic Engine &bull; Automated Defense Assessment &bull; {generation_time}
    </footer>
  </div>

  <script id="raw-markdown-data" type="text/plain">
{escaped_markdown}
  </script>

  <script>
    // Theme Toggle Logic (Light / Dark)
    function applyTheme(theme) {{
      document.documentElement.setAttribute('data-theme', theme);
      const icon = document.getElementById('theme-icon');
      const text = document.getElementById('theme-text');
      if (theme === 'dark') {{
        icon.textContent = '☀️';
        text.textContent = 'Light Theme';
      }} else {{
        icon.textContent = '🌙';
        text.textContent = 'Dark Theme';
      }}
      localStorage.setItem('audit_report_theme', theme);
    }}

    function toggleTheme() {{
      const current = document.documentElement.getAttribute('data-theme') || 'light';
      const next = current === 'dark' ? 'light' : 'dark';
      applyTheme(next);
      // Re-render mermaid with appropriate theme
      initMermaid(next);
      mermaid.run();
    }}

    function initMermaid(theme) {{
      mermaid.initialize({{
        startOnLoad: false,
        theme: theme === 'dark' ? 'dark' : 'neutral',
        themeVariables: theme === 'dark' ? {{
          primaryColor: '#1e293b',
          primaryTextColor: '#f8fafc',
          primaryBorderColor: '#38bdf8',
          lineColor: '#94a3b8',
          fontFamily: 'Inter, sans-serif'
        }} : {{
          primaryColor: '#f1f5f9',
          primaryTextColor: '#0f172a',
          primaryBorderColor: '#0284c7',
          lineColor: '#334155',
          fontFamily: 'Inter, sans-serif'
        }}
      }});
    }}

    // Check saved theme
    const savedTheme = localStorage.getItem('audit_report_theme') || 'light';
    applyTheme(savedTheme);
    initMermaid(savedTheme);

    // Parse Markdown using Marked.js
    const rawJsonStr = document.getElementById('raw-markdown-data').textContent.trim();
    let rawMarkdown = "";
    try {{
      rawMarkdown = JSON.parse(rawJsonStr);
    }} catch (e) {{
      rawMarkdown = rawJsonStr;
    }}

    const parsedHtml = marked.parse(rawMarkdown);
    const container = document.getElementById('report-output');
    container.innerHTML = parsedHtml;

    // Convert language-mermaid blocks to mermaid divs
    document.querySelectorAll('pre code.language-mermaid').forEach((block) => {{
      const pre = block.parentElement;
      const mermaidDiv = document.createElement('div');
      mermaidDiv.className = 'mermaid';
      mermaidDiv.textContent = block.textContent;
      pre.replaceWith(mermaidDiv);
    }});

    mermaid.run();

    function copyMarkdown() {{
      navigator.clipboard.writeText(rawMarkdown).then(() => {{
        alert("Markdown report successfully copied to clipboard!");
      }}).catch(err => {{
        console.error("Failed to copy: ", err);
      }});
    }}
  </script>
</body>
</html>
"""
    return html_template


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Autonomous AI Security & Compliance Report Generator (Groq LLM + Enterprise Rule Engine)",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "-k", "--api-key",
        dest="api_key",
        help="Groq API Key (or set GROQ_API_KEY environment variable)",
        default=None,
    )
    parser.add_argument(
        "-o", "--output-dir",
        dest="output_dir",
        help="Path to testing output directory containing engine JSONs",
        default="output",
    )
    parser.add_argument(
        "-s", "--session-id",
        dest="session_id",
        help="Specific session ID or SPI subfolder to audit (optional)",
        default=None,
    )
    parser.add_argument(
        "-r", "--report-dir",
        dest="report_dir",
        help="Directory where generated reports are persisted",
        default="report",
    )
    parser.add_argument(
        "-m", "--model",
        dest="model",
        help="Groq LLM model identifier",
        default="llama-3.3-70b-versatile",
    )
    parser.add_argument(
        "--format",
        dest="format",
        choices=["both", "markdown", "html"],
        help="Output format to persist",
        default="both",
    )
    parser.add_argument(
        "--compact",
        dest="compact",
        action="store_true",
        help="Force high-density compact JSON context to preserve token limits",
    )
    parser.add_argument(
        "--dry-run",
        dest="dry_run",
        action="store_true",
        help="Run offline mock simulation and generate report without calling Groq API",
    )
    parser.add_argument(
        "-v", "--verbose",
        dest="verbose",
        action="store_true",
        help="Enable verbose diagnostic logging",
    )

    args = parser.parse_args()

    # Load environment variables (.env file support)
    load_env_file()

    output_dir = Path(args.output_dir)
    report_dir = Path(args.report_dir)
    report_dir.mkdir(parents=True, exist_ok=True)

    print(colored("=" * 72, "cyan"))
    print(colored("  ENTERPRISE IPSEC & IKEV2 SECURITY AUDIT REPORT GENERATOR", "cyan", attrs=["bold"]))
    print(colored("=" * 72, "cyan"))
    print(f"[*] Scanning output directory: {output_dir.resolve()}")
    if args.session_id:
        print(f"[*] Target Session Filter:    {args.session_id}")
    print(f"[*] Target Groq Model:        {args.model if not args.dry_run else 'OFFLINE (Dry-Run)'}")

    # Discover and load all session artifacts
    session_data = load_all_session_data(output_dir, args.session_id)
    loaded = session_data["loaded_data"]
    file_metadata = session_data["file_metadata"]

    loaded_count = len([k for k, v in loaded.items() if v is not None])
    if loaded_count == 0:
        print(colored(f"\n[ERROR] No valid test JSON reports were found in '{output_dir}'.", "red"))
        print("Please run the testing pipeline or tests to generate session artifacts before generating a report.")
        sys.exit(1)

    print(colored(f"[+] Discovered and ingested {loaded_count} analytical JSON source(s):", "green"))
    for f in file_metadata:
        print(f"    - {f['role']:<18} : {f['filename']} ({f['size_bytes']:,} bytes)")

    # Extract high-level metrics
    metrics = extract_executive_metrics(loaded)
    print(f"[*] Identified Session SPI:   {metrics['session_id']}")
    print(f"[*] Cryptographic Posture:    {metrics['crypto_posture']} (Anchor: {metrics['best_anchor']})")
    print(f"[*] RFC Compliance Status:    {metrics['rfc_status']} (Passed: {metrics['passed_rules']}, Failures: {metrics['failed_rules']})")

    report_markdown = ""

    if args.dry_run:
        print(colored("\n[*] DRY-RUN MODE: Generating synthetic audit report from active metrics...", "yellow"))
        report_markdown = generate_mock_report(metrics)
    else:
        # Resolve API Key
        api_key = args.api_key or os.environ.get("GROQ_API_KEY")
        if not api_key:
            print(colored("\n[!] Groq API Key was not provided via CLI flag or GROQ_API_KEY environment variable.", "yellow"))
            try:
                api_key = input("Enter your Groq API Key: ").strip()
            except (KeyboardInterrupt, EOFError):
                print("\nAborted.")
                sys.exit(1)

        if not api_key:
            print(colored("\n[ERROR] A valid Groq API key is required to generate the report.", "red"))
            print("Please provide it via one of the following methods:")
            print("  1. CLI parameter:    python generate_report.py --api-key gsk_...")
            print("  2. Environment var:  $env:GROQ_API_KEY='gsk_...' (PowerShell) or export GROQ_API_KEY='gsk_...'")
            print("  3. .env file:        Add GROQ_API_KEY=gsk_... to a .env file in the workspace root")
            print("  4. Dry-run test:     python generate_report.py --dry-run")
            sys.exit(1)

        print("\n[*] Assembling comprehensive prompt context with empirical session metrics...")
        system_prompt, user_prompt = build_groq_prompts(loaded, metrics, file_metadata, compact=args.compact)

        print(f"[*] Connecting to Groq Cloud API ({args.model})...")
        client = Groq(api_key=api_key)

        t0 = time.time()
        completion = None

        # Attempt call with primary model and prompt
        try:
            completion = client.chat.completions.create(
                model=args.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.2,
                max_tokens=8192,
            )
        except Exception as e:
            err_msg = str(e)
            logger.warning("Primary attempt failed: %s", err_msg)

            # Check if rate-limited or TPM exceeded; auto-switch to compact prompt
            if ("rate_limit" in err_msg.lower() or "tpm" in err_msg.lower() or "tokens" in err_msg.lower()) and not args.compact:
                print(colored("[!] Rate limit / TPM limit detected. Retrying with high-density compact payload...", "yellow"))
                sys_p_compact, usr_p_compact = build_groq_prompts(loaded, metrics, file_metadata, compact=True)
                try:
                    completion = client.chat.completions.create(
                        model=args.model,
                        messages=[
                            {"role": "system", "content": sys_p_compact},
                            {"role": "user", "content": usr_p_compact},
                        ],
                        temperature=0.2,
                        max_tokens=8192,
                    )
                except Exception as ce:
                    logger.error("Compact payload retry failed: %s", ce)

            # Fallback models if primary model still failed
            if completion is None:
                fallback_models = ["llama-3.1-70b-versatile", "llama-3.1-8b-instant"]
                for fallback in fallback_models:
                    if fallback == args.model:
                        continue
                    print(colored(f"[!] Retrying with fallback model: {fallback}...", "yellow"))
                    try:
                        sys_p_fb, usr_p_fb = build_groq_prompts(loaded, metrics, file_metadata, compact=True)
                        completion = client.chat.completions.create(
                            model=fallback,
                            messages=[
                                {"role": "system", "content": sys_p_fb},
                                {"role": "user", "content": usr_p_fb},
                            ],
                            temperature=0.2,
                            max_tokens=8192,
                        )
                        args.model = fallback
                        break
                    except Exception as fe:
                        logger.error("Fallback to %s failed: %s", fallback, fe)

        if completion is None:
            print(colored("\n[FATAL] Unable to complete LLM synthesis via Groq. Please verify API key and rate limits.", "red"))
            sys.exit(1)

        duration = time.time() - t0
        report_markdown = completion.choices[0].message.content or ""
        prompt_tokens = getattr(completion.usage, "prompt_tokens", "N/A")
        completion_tokens = getattr(completion.usage, "completion_tokens", "N/A")
        total_tokens = getattr(completion.usage, "total_tokens", "N/A")
        print(colored(f"[+] Synthesis complete in {duration:.2f}s! Tokens: {total_tokens} (prompt: {prompt_tokens}, completion: {completion_tokens})", "green"))

    # Generate timestamped filenames
    timestamp_str = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    clean_session = re.sub(r"[^a-zA-Z0-9_-]", "_", str(metrics['session_id']))
    base_name = f"security_audit_report_{clean_session}_{timestamp_str}"
    
    report_title = f"IKEv2 / IPsec Cryptographic Audit & Compliance Evaluation"
    generation_timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC+05:30")

    saved_files: list[Path] = []

    # 1. Save Markdown Report
    if args.format in ("both", "markdown"):
        md_file = report_dir / f"{base_name}.md"
        with open(md_file, "w", encoding="utf-8") as f:
            f.write(report_markdown)
        saved_files.append(md_file)

        # Update pointer to latest markdown report
        latest_md = report_dir / "latest_report.md"
        with open(latest_md, "w", encoding="utf-8") as f:
            f.write(report_markdown)

    # 2. Save Standalone HTML Report
    if args.format in ("both", "html"):
        html_file = report_dir / f"{base_name}.html"
        html_content = generate_html_report(
            markdown_content=report_markdown,
            metrics=metrics,
            report_title=report_title,
            generation_time=generation_timestamp,
            model_name=args.model if not args.dry_run else "Offline Simulator",
        )
        with open(html_file, "w", encoding="utf-8") as f:
            f.write(html_content)
        saved_files.append(html_file)

        # Update pointer to latest HTML report
        latest_html = report_dir / "latest_report.html"
        with open(latest_html, "w", encoding="utf-8") as f:
            f.write(html_content)

    print(colored("\n" + "=" * 72, "green"))
    print(colored("  REPORT GENERATION SUCCESSFUL!", "green", attrs=["bold"]))
    print(colored("=" * 72, "green"))
    for sf in saved_files:
        print(f"  [>] {sf.resolve()}")
    if args.format in ("both", "html"):
        print(f"  [>] Open interactive dashboard: {(report_dir / 'latest_report.html').resolve()}")
    print("=" * 72 + "\n")


if __name__ == "__main__":
    main()
